### ISSUE TITLE
Show Page Name Instead of Default Heading

### ISSUE THREAD

**Issue by mustajab-ikram** [twentyhq/twenty#1294]
### Description:

In the current setup of our app, the page title doesn't change by default when navigating to different pages. To ensure proper SEO and provide a clear indication of the page's content, we should consider showing the page name in the title instead of relying on a default heading.

![image](https://github.com/twentyhq/twenty/assets/94978425/fda30921-2944-46ae-8f57-f126822c9f59)

### Steps to Reproduce:

1. Navigate to any page within the application.
2. Observe the browser tab title – it remains static and doesn't reflect the current page's content.

### Expected Behavior:

The browser tab title should dynamically update to show the name of the current page, providing better context for users and search engines.

**Comment by mustajab-ikram** [comment]
### Proposed Solution:
Implement a mechanism to dynamically update the page title based on the current route. This can be achieved using the react-helmet-async library, which allows us to manage the document head including the title tag. 

> The use of react-helmet-async is a common practice in React applications to manage document metadata, including the title.

**Comment by FelixMalfait** [comment]
That would be great @mustajab-ikram! I hadn't thought of this. Thanks a lot

We want people to make the CRM their own so I'm not sure if we should add " | Twenty" or " – Twenty" like some people are doing. I'd say we should go without it so that people can truly feel it's a dedicated space for their company (+ we still have the 20 favicon)
