### ISSUE TITLE
Feature Request: Members should not be allowed to remove the owner of workspace

### ISSUE THREAD

**Issue by mhamzabcs** [twentyhq/twenty#1394]
Members shouldn't be allowed to remove other members as well as owner of the workspace. Only owner of workspace should be allowed to do so.

![image](https://github.com/twentyhq/twenty/assets/20185057/042416ab-47ab-440c-a5ff-2e1e55cd7038)

Please add to your backlog, thank you!

**Comment by charlesBochet** [comment]
@FelixMalfait @Bonapara what do you think of this one? I feel that if we want do introduce a notion of workspace owner with more permissions, we would also need to be able to transfer this ownership

**Comment by Bonapara** [comment]
Added "design needed" tag, will try to work on this soon

**Comment by FelixMalfait** [comment]
@Bonapara just a ping to make sure you have read my comment! This is not a lightweight design task imo, it needs to be designed in the context of roles/permissions which is probably at least a week of design work

**Comment by Bonapara** [comment]
@FelixMalfait I red your comment. Don't you think we can make a V1 with Owner, Admin, Member and enrich it later with more specific "user profiles" as we grow?

**Comment by FelixMalfait** [comment]
@Bonapara I think it's the type of feature where we really need to have the end vision and walk back from there. Doing an overly simplistic design could lead to engineering decisions that are hard to fix later on (introducing the concept of "owner" as a boolean is an example of something that I think would be bad - unless if related to billing or other areas than pure permissions ;  and permissioning is an area that is particularly hard to change because you need to give users upfront notice etc unlike typical UI changes).

**Comment by Bonapara** [comment]
@FelixMalfait Introducing a boolean would be a bad idea indeed, but what if we introduce a "User type" table (One user has one user type), "user type" having different boolean value such as: "Can edit users? = True".  This would enable us to easily add/edit rights for a user type and easily create some new "user type" later on.

We could also anticipate the fact (but not develop it) that we may like to override the "User type" permission for a given user later by giving "custom permissions"

I have the feeling a such system could be easy to scale, and that we don't take so much risks starting with a "admin user type" but maybe I'm missing something.

**Comment by FelixMalfait** [comment]
@Bonapara  Yes the typical long-term structure would  probably involve:
- Application permissions 
- Object-level permissions
- Field-level permissions
- PermissionSets
- Roles
- UserGroups
- Roles x {UserGroups + Users}

I'm not saying we shouldn't do it, I also think it's high priority. But doing 2 versions (long-term + short-term) would help get the right engineering design.

For example when you say "override the user type for a given user" it has a particular meaning. Is that really what you want to do? I don't think we want to let a user be outside of a role ; and do you want the override to be like a seeded permissions table that we edit directly or should their be a central source of truth for what these roles really mean (could be useful to keep the "semantic value" of the role and not just seeds if we need to introduce permissions later on) that we really override? Etc.

**Comment by FelixMalfait** [comment]
Closing for now and we'll reopen when we tackle https://github.com/twentyhq/twenty/issues/869

**Comment by marcelocbf** [comment]
Hi team,

Is this something you are planning to implement in the near future? It's been a year since this has been closed. I signed up for the cloud version but besides #869 that would be very beneficial to me I can live without it for some time, bringing my team in and someone coming and deleting my account as the owner (billing) or deleting the workspace is a major problem for me

**Comment by FelixMalfait** [comment]
Thanks for the feedback@marcelocbf I agree permissions are super important. We've been pushing back on this because we want to do it well, with row/column-level permissions and the more mature the data modeling system is, the less risk there is that we build it the wrong way. I think the system is mature enough now but we are busy working on workflows (which will be a very very cool feature once complete imo) so permissions will only be a priority next year
