### ISSUE TITLE
I can add a favorite directly from my table

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1720]
## Scope & Context

When we are on the table page.

## Current behavior

We can't add a favorite and we need to go the show page and go all over the top right corner to add a favorite, since this a neat feature, it would be nice to make it easier to access.

## Expected behavior

We can add / remove a favorite from the table view.

We need to know where this feature would be better put in the current UI.

- An easy implementation that is intuitive could be in the context menu when we right click on a table, that would make all the lines favorite / unfavorite
- We could also have a star checkbox / column
- Any other idea ?

**Comment by lucasbordeau** [comment]
@Bonapara

**Comment by Bonapara** [comment]
Great idea! Let's proceed with the first option, which is to include it in the contextual menu. Here's the design. Please rename the remaining menu items to correspond with the Figma text e.g. "NEW task."

![Screenshot 2023-09-26 at 11 20 35](https://github.com/twentyhq/twenty/assets/19412894/568f695c-62c2-4fa7-bc0b-293e77a2f46f)

**Comment by AyushAgrawal-A2** [comment]
@Bonapara @lucasbordeau 

I was trying to solve this issue, please clarify:-

1. Heart icon is used for favorite on the show page. Should the same be used here or Star icon as shown in the figma design screenshot?
2. If a company/person is already marked favorite, then the context menu should show "Remove from favorites" with a filled heart / start icon?
3. What if multiple rows are selected, some of which are already marked favorite. What should be the menu item and behavior?
4. What if multiple rows are selected, where all/none of them are already marked favorite. What should be the menu item and behavior?

Because the context menu can appear for multi-select items there will always be ambiguity. We can check if it is multi select and not display favorite line item at all.
Or
I propose to show a favorite button to appear upon hovering over the Chip Cell like a pencil icon shows up for Editable Cell in display mode.

Please advise.

**Comment by Bonapara** [comment]
Hi @AyushAgrawal-A2 
1) Thanks for noticing the point, indeed we should use the "heart" icon as on the Show page. New Figma below
2) Well noticed again. We should do this and display the "Heart-off" icon. Figma below
3) & 4) To ease things, we should only display the option if one line is selected.

### Screenshots
Add to favorites
![Screenshot 2023-09-27 at 10 29 19](https://github.com/twentyhq/twenty/assets/19412894/d878884d-a2a7-49d0-bf02-08a2fedb5a4b)

Remove from favorites
![image](https://github.com/twentyhq/twenty/assets/19412894/39d9eb40-fb92-4c77-905c-5bf52bb69606)

**Comment by AyushAgrawal-A2** [comment]
Hi @Bonapara @lucasbordeau
I have this working now :

https://github.com/twentyhq/twenty/assets/54364088/06838b98-1504-4ace-9294-62ea89127782

I have another doubt. After clicking on the favorite button, 
1. should the context menu remain open or it should close?
2. should the row selection remain or it should be cleared?

Also while navigating the code for this issue I found another bug. On the Show page -> Plus Icon -> both Task and Note open the New Note right drawer. It is a one-word typo in ShowPageAddButton.tsx. Should I fix it in this PR ?

https://github.com/twentyhq/twenty/assets/54364088/26b3b85c-a1d7-43b2-882c-290105ea7394

**Comment by lucasbordeau** [comment]
@AyushAgrawal-A2 Please let's createa bug issue so that the community can pick this as a good first issue !
