### ISSUE TITLE
On click outside should listen to mouse down and not mouse up

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1728]
## Scope & Context

We have a generic hook to listen for clicks outside of an element : `useListenClickOutside`.

## Current behavior

This can cause problems like when selecting a text and ending outside of the input : 

https://github.com/twentyhq/twenty/assets/26528466/c9c76e6b-f52b-4e05-bc5b-a18124e5c5c0

## Expected behavior

We want this mechanism to be prevented by using an on mouse down instead of mouse up or click.

As it might impact a lot of features, the best way would be to be able to pass the type of event we want, either : `mouse-up` or `mouse-down` as a string literal type, and keep the actual event as the default event type.

We could also fix the current implementation which seems to not match between mobile and web : 

```tsx
 document.addEventListener('mousedown', handleClickOutside);
 document.addEventListener('touchend', handleClickOutside, {
```

`mousedown` should correspond to `touchstart` and `mouseup` or `click` to `touchend`.

**Comment by lucasbordeau** [comment]
@AyushAgrawal-A2 Here is the new issue : https://github.com/twentyhq/twenty/issues/1734

**Comment by AyushAgrawal-A2** [comment]
@lucasbordeau 
As per my understanding, there are 2 event listeners
1. `useListenClickOutside` hook - "click" event listener on the document with capture true.
2. `EditableCellDisplayContainer` div container - "onClick" event on the div of editable cells of the table.

On any "click" event, if "isCurrentCellInEditMode" is true, the handleClickOutside method stops the event propagation. Hence preventing "click" event in `EditableCellDisplayContainer` div container, which prevents any other cell from going directly into edit mode.

In my PR I changed the `useListenClickOutside` hooks event to "mousedown", hence only "mousedown" event propagation was getting stopped on outside click. The "click" event still fires in `EditableCellDisplayContainer` div container and hence the outside cell goes directly into edit mode. Both events are linked and need to be listening to the same event.

I tried just changing the `EditableCellDisplayContainer` div container's event to "onMouseDown", the original problem remains that the useListenClickOutside` hook, which is still listening for click event, treats text selection bug as an outside click because the final pointer location is outside of the current element. Hence the div container closes edit mode.

Both events need to be switched to "mousedown" as they are linked.

Also in my PR I had set the default prop for `useListenClickOutside` hook to listen for "mousedown" event. I can retain "click" event as default and pass "mousedown" as props for this use case alone, preventing any side effects.

I have tried this locally and this works functionally and also passes tests.
Please advise.
