### ISSUE TITLE
UI ChipDisplay depends on non UI components

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#1847]
## Scope & Context

In the UI folder ChipDisplay depends on CompanyChip and PersonChip that are implemented outside of the UI folder.

## Technical inputs

We thought about using the React context api to define a mapper inside the FieldContext Provider : 

Example : 

Inside front/src/modules/companies/components/CompanyBoardCard.tsx : 

```
<FieldContext.Provider
                value={{
                  entityId: boardCardId,
                  recoilScopeId: boardCardId + viewField.key,
                  fieldDefinition: {
                    ...
                    displayMapper: (dataObject: Company) => {
                      return {
                        name: dataObject.displayName,
                        pictureUrl: dataObject.avatarUrl,
                        variant: "squared"
                      }
                    }
```

Inside front/src/modules/ui/field/meta-types/display/components/RelationFieldDisplay.tsx : 

```
import { EntityChip } from '@/ui/chip/components/EntityChip';
import { useRelationField } from '../../hooks/useRelationField';

export const RelationFieldDisplay = () => {
  const { fieldValue, fieldDefinition } = useRelationField();
  const {displayMapper} = fieldDefinition;
  return (
    <EntityChip {...displayMapper(fieldValue)}/>
  );
};
```

We would then also need to refactor ChipDisplay.

We also thought about enabling to pass a custom ChipComponent to the FieldContext, but we thought that it could be too permissive for the end user (for example, modifying the code and passing another component).

**Comment by lucasbordeau** [comment]
The **mapper pattern should be avoided as much as possible** as it often creates too custom, too hard to read and difficult to refactor zones, for problems that could be tackled by thinking about why the current API needs a mapper.

The mapper pattern can be replaced by rethinking the displaying code and pulling out the data structure it needs in a simple type that can be used higher in contexts or parent components.

In this precise use case, the mapper would add another layer of mapping on an already existing mapping layer in `ChipDisplay`, which would create redundancy.

The problem is that CompanyChip and PersonChip were created as wrappers on top of `EntityChip`, to abstract `linkToEntity` and `avatarType` property.

We could remove CompanyChip and PersonChip (and probably ChipDisplay) and instead pass `linkToEntity` and `avatarType` directly to an `EntityChip` component and delete `ChipDisplay`. 

`linkToEntity` and `avatarType` could be put in the FieldContext.
