### ISSUE TITLE
Force usage of `docker compose` instead of `docker-compose` 

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#1899]
## Scope & Context

Some users have reported problems with `docker-compose` being too old for our docker compose file version.

## Technical inputs

Should we force people to use the new integrated `docker compose` command in the latest docker engine version, or instead keep backward compatibility by using an older docker compose file version ?

**Comment by lucasbordeau** [comment]
@charlesBochet @FelixMalfait What are your thoughts ?

**Comment by FelixMalfait** [comment]
OK for me to support `docker compose` only, it seems acceptable! But I don't have a strong expertise

**Comment by BOHEUS** [comment]
From what I know, `docker compose` is basically a rewrite in Go of original `docker-compose` which was written in Python and there is no downside when moving to newer version. Also, Linux users have to install `docker-compose` aside from docker engine itself if they want to use it older version as only newer is shipped with docker. 
Worth mentioning, `docker compose` is faster than `docker-compose` as it uses advanced cache and parallelism to reduce building times and newer version has backwards compatibility.

Older version supports max 3.7 version, that's why I had to change the docker-compose.yml when trying to build it locally with docker-compose

**Comment by charlesBochet** [comment]
LGTM, taking a look at the PR today

**Comment by charlesBochet** [comment]
This has been fixed, thanks @BOHEUS :)
