### ISSUE TITLE
Docker commands are slow and difficult to follow

### ISSUE THREAD

**Issue by dmikushin** [twentyhq/twenty#2080]
Thanks for the great project, unfortunately the deployment effort ruins the initial impression:

1. Frontend startup is EXTREMELY SLOW. Please take any docker container of your choice and check how long it starts. Yours stats 10x longer. Maybe some action needs to be moved to build step, overall some bad design exists out there.

2. Frontend and server containers are made to start in foreground. Are you serious?? Who is doing it like this, I don't know what to say.

3. [Docker instructions](https://docs.twenty.com/contributor/local-setup/docker-setup#step-4-migrate--seed) are misleading:

* This statement refers to non-existing targets:

> Before running the project, you need to initialize the database by running the migrations and seed.

* These two targets no longer exist either:

```
make server-database-setup
make server-database-reset
```

* This statement is not clear:

> generate prisma client, and seed

Perhaps it implies doing `make server-prisma-generate && server-prisma-seed`, but it fails with the following error:

```
^
PrismaClientKnownRequestError: 
Invalid `prisma.$queryRawUnsafe()` invocation:


Raw query failed. Code: `42P01`. Message: `relation "metadata.data_source_metadata" does not exist`
    at oa.handleRequestError (/app/server/node_modules/@prisma/client/runtime/binary.js:234:6479)
    at oa.handleAndLogRequestError (/app/server/node_modules/@prisma/client/runtime/binary.js:234:5908)
    at oa.request (/app/server/node_modules/@prisma/client/runtime/binary.js:234:5787)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Proxy._request (/app/server/node_modules/@prisma/client/runtime/binary.js:237:10500)
    at async seedWorkspaces (/app/server/src/database/seeds/workspaces.ts:28:3)
    at async seed (/app/server/src/database/seeds/index.ts:13:3) {
  code: 'P2010',
  clientVersion: '4.13.0',
  meta: {
    code: '42P01',
    message: 'relation "metadata.data_source_metadata" does not exist'
  }
}

An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node src/database/seeds/index.ts
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [Makefile:51: server-prisma-seed] Error 1
```

So I conclude something different should be done, but it can't be figured out from the given instruction.

Please make adjustments to your deployment, currently it has multiple really silly flaws. It would be a pity to give up such a nice project to bad installation experience. :+1: :+1: :+1:

**Comment by khakimov** [comment]
Sorry to hear about your experience with the project, I will look into it.

The project currently is trying to swtich from Prisma to TypeORM and I think it makes a bit complicated deployment for everyone.

**Comment by charlesBochet** [comment]
@dmikushin Could you please fix rephrase your issue in a less aggressive style, this is a friendly community here ;)

@khakimov @dmikushin we have updated the docs and instructions this morning but it's not deployed to docs.twenty.com, that's why the command are not up-to-date, I'm triggering a deploy.

Regarding 3. feel free to make a PR to the doc if you feel it can be improved, suggestions are welcomed.

Regarding 1. None of us is experiencing the issue, what is taking time, 
- the docker build (do you have a slow network bandwidth?). Yarn dependencies are indeed around 2GB, postgres container is heavy too, etc...
- or the docker run (up) ? It should not take more than 30sec to run the first time as its building its cache. Next times should be ~5seconds on Mac M2 configuration

Regarding 2. Not sure to know what you mean here. To me it provides a good developer experience to be able to see your logs direclty and kill your front watch and server watch easily to restart them if you are updating some part of the code that are not captured by the watch (env variables update, yarn package addition, ...). We could also provide a stop command for each of them but I don't think it improves the developer experience.

Overall, I'm happy to discuss any suggestions that you would propose, also remember this is an open-source project so you contributions are welcomed ;)

**Comment by dmikushin** [comment]
> Could you please fix rephrase your issue in a less aggressive style, this is a friendly community here

No aggression at all. It's critics. Serious issue deserves strong critical statement.

I suppose you are the project owner, so it's obvious that you like most of it. But users' opinions can help you more than your own, you should understand this as a CTO.

I've iterated over multiple opensource CMS recently, JIRA and Confluence alternatives as well. And this project has _worst_ deployment experience.

**Comment by dmikushin** [comment]
This is what I see during the first few minutes of the frontend startup:

![Screenshot from 2023-10-16 23-53-06](https://github.com/twentyhq/twenty/assets/5672874/29a98261-0308-4116-b9ea-a1732c2a932e)

Idle CMS eats 300% of CPU, this is probably a world record. I think at startup something happens, what is not supposed to be a part of the startup. I insist that I deploy many projects like yours, and never seen anything like this before.
