### ISSUE TITLE
[COMPLAINT] Team Member Closes Valid Issue 

### ISSUE THREAD

**Issue by abebeos** [twentyhq/twenty#2091]
### Status

CTO closes a valid issue (by @dmikushin) due to 'sensitivity issues':

https://github.com/twentyhq/twenty/issues/2080#issuecomment-1766629844

A technical issue cannot be closed if it is valid (especially those affecting performance).

### Expected

* Have far(!) more respect for the individuality of expression styles
* Reopen the issue
* Add some (liberality) policies for team-members

**Comment by charlesBochet** [comment]
Hi @abebeos, 

This project is open-source, it is meant to be a **collaborative** and **friendly** place. 
I have closed the previous issue because of the tone which is not suitable for the mindset of this repository. 

I do respect the person but we cannot let, whoever might be the target of it. Here are a few examples: 
- "But users' opinions can help you more than your own, you should understand this as a CTO." => this phrasing is aggressive.
- currently it has multiple really silly flaws => also agressive
- "Frontend and server containers are made to start in foreground. Are you serious?? Who is doing it like this, I don't know what to say." ==> aggressive too

**The issue can be re-opened with a more polite tone and we would happily work on it.**

We will add a code of conduct to make it clear on the repository, probably similar to this one which looks great: https://github.com/vuejs/vue/blob/dev/.github/CODE_OF_CONDUCT.md

I will also close this issue but feel free to comment on it if you want to discuss further as long as it stays polite.

**Comment by lazaridiscom** [comment]
@charlesBochet , you seriously process a complaint against you by yourself, and close it?

Here is my tone for this: you are an IT-fascist.

**Comment by abebeos** [comment]
@charlesBochet , you really need to reopen this complaint.

Naturally, you cannot process a complaint against you by yourself.

You understand why?

**Comment by abebeos** [comment]
@Bonapara , @FelixMalfait , @Weiko => fix this.

**Comment by abebeos** [comment]
> * "But users' opinions can help you more than your own, you should understand this as a CTO." => this phrasing is aggressive.

you are delusional, if you find this aggresive.

> * currently it has multiple really silly flaws => also agressive

I assess it as "casual".

> * "Frontend and server containers are made to start in foreground. Are you serious?? Who is doing it like this, I don't know what to say." ==> aggressive too

Maybe the author is one (or two) leagues above you? Listen and learn.
