### ISSUE TITLE
Dropdown menu of header table does not close after hide column. 

### ISSUE THREAD

**Issue by ttlpta** [twentyhq/twenty#2151]
## Bug Description
- Click header of table to show dropdown then select option hide.
- Click button Plus in header of the last column of the table, and select column which has just hidden.
- The column show with the dropdown menu.
![image](https://github.com/twentyhq/twenty/assets/9917124/ef30afe5-728d-44c7-9b1f-baae83239eb6)

## Expected behavior

- The dropdown menu of the header also close when this column hidden.

## Technical inputs
- N/A

**Comment by FelixMalfait** [comment]
I'm able to reproduce it too. Thanks for the report!

**Comment by FelixMalfait** [comment]
I'm seeing a second display bug which is worse: 
<img width="317" alt="Screenshot 2023-10-20 at 18 42 21" src="https://github.com/twentyhq/twenty/assets/6399865/557a8b00-ee91-4585-b1df-e23d5d1c8bed">
The (+) dropdown seems to be stuck within the cell, making the top bar height a lot bigger than it should be. 
Since it's a similar problem, let's try to tackle it as part of this issue if it's an easy fix (if not let's create an other issue)

**Comment by ttlpta** [comment]
@FelixMalfait I've already fixed this issue. Pls help me review this PR https://github.com/twentyhq/twenty/pull/2177
