### ISSUE TITLE
Adjust company's chip clicking behavior on People detail pages

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#2720]
I heard this feedback during a customer call this morning.

When I'm on a person's page, I should be able to click and go to the companies' page easily.=

<img width="214" alt="Screenshot 2023-11-27 at 09 51 19" src="https://github.com/twentyhq/twenty/assets/6399865/91de67e5-3e8b-4d2c-bd00-2ae4e0f2d4ab">

cc @Bonapara

**Comment by Bonapara** [comment]
Yes, indeed! The company chip's behavior is incorrectly implemented. Clicking on the chip should **redirect to the company's page** (instead of opening the company picker). To edit the company relation, you should click on the **pen icon button** located at the right of the chip.

![CleanShot 2023-11-27 at 09 54 41@2x](https://github.com/twentyhq/twenty/assets/19412894/2efc7700-e301-4d6f-9e34-20646fd1adee)

**Comment by charlesBochet** [comment]
That's right! I've also noticed this regression last week. I believe it's because the link is not passed to the chip anymore

**Comment by FelixMalfait** [comment]
@nimraahmed are you going to work on this or do you want me to un-assign you? Thanks 🙏

**Comment by nimraahmed** [comment]
@FelixMalfait you can unassign it for now; if it's not resolved in a week or so then i'll take it up again

**Comment by FelixMalfait** [comment]
Closing as I believe #2386 references the same issue
