### ISSUE TITLE
Improve REST API syntax

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#3035]
2 things we could improve to the newly released API:
(1) Remove edge/node keywords ; people who don't know GraphQL are not familiar with those concepts - and REST usually don't have them.
(2) Introduce versioning? Either by adding /v1.0/ in the URL or passing the version as headers? This seems to be the norm in REST but not in GraphQL. GraphQL recommends "continuous evolution of the schema" which tbh I'm not convinced is a good idea (you need to cleanup sometimes). So if we don't have versioning in GraphQL the only point of versioning REST would be for rare structural changes relative to the REST syntax like item (1).

**Comment by MrSharpp** [comment]
My suggestion would be using option (2), as REST API versioning is the norm and it makes the schema consistent specific to a version.

**Comment by FelixMalfait** [comment]
Sorry it wasn't clear, it wasn't really an "OR" between (1) and (2).
We should fix (1) for sure. 
And for (2) what I meant is that the current REST API is just a wrapper around the GraphQL API, so since our GraphQL implementation doesn't have versioning, I'm not sure if it's worth introducing it for REST. It would still be useful for rare syntax changes like (1), but should we also introduce versioning for GraphQL then? Maybe this deserve more consideration before changing it

**Comment by charlesBochet** [comment]
@FelixMalfait versioning comes at a cost because it means maintaining the previous version (otherwise there is no point versioning). As the Rest API relies on the GraphQL API, and we are actually not versioning at all currently, we should be consistent between the two.

What it would mean to version the API beside adding v1 in both graphql and rest api urls:
- read this url query param or header
- based on this query param load a different graphql schema (as we dynamically generate it we would need to integrate this parameter in our schema builder - likely to create a v1, v2, ... folders in schema builder that would contain the functions specific to v1, v2, etc. ; v1 would contain everything and v2 would be able to overwrite those for example)
- then add this logic to rest two

Short term, we can add v1 just to both API to show that's the direction we want to take but as long as we are still experimenting with the API, I would not version it in practice, this will slow the development

**Comment by charlesBochet** [comment]
Regarding the ticket, we can definitely do (1) + do (2) for both graphql and rest but do not do anything in practice to version the API for now

**Comment by FelixMalfait** [comment]
@charlesBochet good for me! (Your call, I'm also fine with no versioning for now)
