### ISSUE TITLE
Add graphiql explorer plugin in docs graphql api playground

### ISSUE THREAD

**Issue by martmull** [twentyhq/twenty#3087]
## Scope & Context
We want a graphql API explorer in [https://docs.twenty.com/graphql](https://docs.twenty.com/graphql) like we have in [https://api.twenty.com/graphql](https://api.twenty.com/graphql). It is indeed a really useful option

## Current behavior
In [https://docs.twenty.com/graphql](https://docs.twenty.com/graphql) we have:
![image](https://github.com/twentyhq/twenty/assets/29927851/94cf06c1-e6be-4e8c-97b8-44c859c955b9)

## Expected behavior
We want the query explorer plugin like we have in [https://api.twenty.com/graphql](https://api.twenty.com/graphql)
![image](https://github.com/twentyhq/twenty/assets/29927851/589d4049-f6b4-4897-b1ad-6f5fce897140)

## Technical inputs
Add [@graphiql/plugin-explorer](https://www.npmjs.com/package/@graphiql/plugin-explorer?activeTab=readme) plugin to `packages/twenty-docs/src/pages/graphql.tsx`

**Comment by i-am-chitti** [comment]
@martmull Is this still a pending issue to be worked upon? I can see GraphQL explorer on both docs and main site.

**Comment by Jeong-Min-Cho** [comment]
@i-am-chitti It is still a pending issue indeed as I checked.

@martmull This issue can be done easily, but there are some catch-ups.

## Problem 
There were some [lifecycle bugs](https://github.com/graphql/graphiql/commit/bed5fc86173eb0e770f966fa529ee035b97a1349) in graphiql plugins, which includes [@graphiql/plugin-explorer](https://www.npmjs.com/package/@graphiql/plugin-explorer?activeTab=readme) too. This has already been handled by graphqiql team.

Thus, we need to use an older version of `@graphiql/plugin-explorer`.

## Current situation

Since it depends on `graphiql` library which `Twenty` uses ["graphiql": "^2.4.7"](https://github.com/twentyhq/twenty/blob/f36fa9aa147f216537ad3a51bec2913b0988a957/packages/twenty-docs/package.json#L25C11-L25C11) 
![image](https://github.com/twentyhq/twenty/assets/9837449/c2796139-2dce-45f6-b7a4-e282f821a2f0)
This was released in May 2023 (https://www.npmjs.com/package/graphiql?activeTab=versions).

![image](https://github.com/twentyhq/twenty/assets/9837449/f1c4a3dc-9291-4402-b97b-1c5acee3ce83)

So, I tested with the `@graphiql/plugin-explorer` version of 0.1.20 which was also released in May 2023 (https://www.npmjs.com/package/@graphiql/plugin-explorer?activeTab=versions).

The result was not satisfying for me.

![image](https://github.com/twentyhq/twenty/assets/9837449/57e532ef-30a7-4103-8bac-ca9d0f981be3)

It throws an error that might be solvable, but I did not want to investigate further for two reasons.

1. Updating `@graphiql/plugin-explorer` will require another update the code in the future
It is because that the usage of `@graphiql/plugin-explorer` has been changed by graphqiql team - [Link](https://github.com/graphql/graphiql/commit/bed5fc86173eb0e770f966fa529ee035b97a1349)

2. Also updating `graphiql` will break the app again
It throws `Attempted import error: 'useOperationsEditorState' is not exported from '@graphiql/react' (imported as 'u').` error.


## Blocker
1. The version of `graphiql` in `twenty-docs` needs to be updated to a later version

## Solution in the future
![image](https://github.com/twentyhq/twenty/assets/9837449/426996d2-dfdc-493d-b830-6c6e52d3895a)
The screenshot above is done by updating `graphiql` to the latest and installed the lastest version of `@graphiql/plugin-explorer`.

You may check my commit in my branch
### Branch
https://github.com/Jeong-Min-Cho/twenty/tree/3087-add-graphiql-explorer-plugin-in-twenty-docs
### Commit
https://github.com/twentyhq/twenty/compare/main...Jeong-Min-Cho:twenty:3087-add-graphiql-explorer-plugin-in-twenty-docs


## Now what?
1. We should wait for the blocker to be unblocked
2. Copy-paste my code or adapt my code to your commit
3. Create a pull request

**Comment by martmull** [comment]
Hey @Jeong-Min-Cho thank you for your very clear explanation. Do you see any breaking changes in the playground when updating graphiql to version 3.0.10?
If no I might say we don't have any blocker to update graphiql version and add the Explorer plugin. @charlesBochet what do you think?

**Comment by Jeong-Min-Cho** [comment]
> Hey @Jeong-Min-Cho thank you for your very clear explanation. Do you see any breaking changes in the playground when updating graphiql to version 3.0.10?

Hello, thanks for coming back to this. I personally do not see any breaking changes by updating it.

**Comment by martmull** [comment]
@Jeong-Min-Cho Seen with @charlesBochet, we would be glad to get your changes in our code base. Do you feel like creating a PR linked to that issue?
Best

**Comment by Jeong-Min-Cho** [comment]
@martmull 
Of course, the pull request is up as you asked! 👍
