### ISSUE TITLE
Creating a new object - not able to pick relation typr

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [twentyhq/twenty#3172]
Im using v2.2.0 opensource version. 

While creating a new object or adding a new field in existing object, im not able to see the relation type.

**Comment by FelixMalfait** [comment]
Yes this is still behind feature flag `IS_RELATION_FIELD_TYPE_ENABLED`. Should be stable and feature flag will be removed very soon

**Comment by cocobeach** [comment]
Hi I am having a problem with targeting the "Name"field in a relationship of 1 Opp TO-MANY Services because it won't let me bind my custom field "Opportunity/Service" to the Name of my custom object "Services", here is the ERROR: 

duplicate key value violates unique constraint "IndexOnNameObjectMetadataIdAndWorkspaceIdUnique"

Can't we name the default "Name" field differently, like CustomServiceName, where CustomService is the name of the the New custom Service so to make them unique?

**Comment by FelixMalfait** [comment]
cc @charlesBochet

**Comment by cocobeach** [comment]
Did I say smth stoopid? 👀

**Comment by FelixMalfait** [comment]
Haha no 😂 — just that @charlesBochet will be able to answer this better than I would

**Comment by charlesBochet** [comment]
Good point!
So, right now we force all custom objects to have a "Name" field that you cannot remove from the UI. 
The reason why is that in many places in the app (relation picker, command menu, ...), we need to display what we call the "record identifier". For a company, it will be the Name. For a Person, it will be First Name + Last Name. For a custom object, it will be the Name for now.

Our plan is to let the user pick (for each object) what field should be considered as the record label identifier. The backend is ready but the Settings UI part has not been done yet.

You can check this figma: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=11338%3A64083&mode=dev

I believe we also have tickets #2489. This will likely be tackled next week (happy to assist you if you want to help!)

**Comment by charlesBochet** [comment]
In the meantime you can try renaming this field manually in your own database
