### ISSUE TITLE
First cell of index is cropped 

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#3220]
# Current behavior

When creating a new record on an object index, the bottom part of the floating cell is cropped underneath the cell below.

![CleanShot 2024-01-03 at 12 41 37@2x](https://github.com/twentyhq/twenty/assets/19412894/2e73b0ba-4a5b-45b3-b639-81d92488ee1a)

# Desired behavior

The floating cell should be... floating `above` the cell below.

**Comment by Jeong-Min-Cho** [comment]
Hello, I dug up the problem a little.

This is actually a regression from #3147 

https://github.com/twentyhq/twenty/pull/3147/files#diff-1eb42b8c2309ef48fdce276caaf462df213a70c044ed4b5d48bc27c8cd965656R55

![Screenshot 2024-01-04 143332](https://github.com/twentyhq/twenty/assets/9837449/127d9c45-76d7-4f16-89e5-d244e66eda06)
_(I intentionally increased the alpha of the border shadow to view more clearly)_

As you can see that, the first two columns are located at the top of the editing cell field.

I tried a quick fix to resolve such as changing z-index of the children, but since other cells also use the same style, it was not helpful.

I will ping @Muralidhar22 since he worked on the issue. I will try some fixes on my side too while he is looking into this issue.

Thanks

**Comment by Muralidhar22** [comment]
@Jeong-Min-Cho I am not currently working on this issue, if you wanted to discuss anything, am happy to be of help we can connect on twenty discord server.

PS: I can pick this issue if no one started working on this @Bonapara  / @FelixMalfait

**Comment by FelixMalfait** [comment]
Thanks @Jeong-Min-Cho for catching this! Thanks @Muralidhar22, if of one you two can give it a shot amazing :)
