### ISSUE TITLE
Fix tsc in twenty-front and install vite-plugin-checker

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3237]
## Scope & Context

`twenty-front` folder, typechecking.

## Technical inputs

`tsc` is not working anymore on the twenty-front folder. We need to make it work because we're developing without seeing typescript errors on the project level, and that lowers the DX a lot. 

See how to tweak the multiple tsconfig files so that we keep linting and typechecking.

Install [vite-plugin-checker](https://vite-plugin-checker.netlify.app/introduction/getting-started.html) so we have tsc running in parallel with vite.

**Comment by i-am-chitti** [comment]
@lucasbordeau I tried taking a look into this and found that none of the files are part of compilation. This is done by using `--listFilesOnly` flag available on `tsc` command line.
<img width="580" alt="image" src="https://github.com/twentyhq/twenty/assets/60139930/0a1ea4c1-54e8-4a2e-8f17-b7c650118bfc">

But if I directly use the `include` in main tsconfig.json on twenty-front like this - 
```
  "include": ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"],
  "references": [
    // {
    //   "path": "./tsconfig.app.json"
    // },
    // {
    //   "path": "./tsconfig.node.json"
    // },
    // {
    //   "path": "./tsconfig.spec.json"
    // }
  ]
```

The files are getting scanned and tsc is functioning as expected -
<img width="956" alt="image" src="https://github.com/twentyhq/twenty/assets/60139930/00e60e01-f0a6-4373-9efc-d8c476a9a054">
Though, it's scanning `node_modules` too.
Since, this is an issue with tsconfig.json, configuring vite-plugin-checker still won't work. I think all the files are getting excluded due to tsconfig in `references` [here](https://github.com/i-am-chitti/twenty/blob/main/packages/twenty-front/tsconfig.json#L33-L43).

I haven't worked with tsconfig enough. Could you guide me here how should I approach this in order to preserve the references as well as make tsc work.

**Comment by lucasbordeau** [comment]
@i-am-chitti We fixed the issue with the core team, for reference here is the PR : https://github.com/twentyhq/twenty/pull/3289
