### ISSUE TITLE
[Flexible-Schema] I can add an Index decorator to BaseObjectMetadata classes

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#3708]
## Scope & Context

Some queries are quite expensive and we currently have no way to create an index for our standard objects except for FK.
Ideally we should be able to add an [at]Index decorator that will contain the columns we want to index for composite indexes or an [at]Index decorator for each field if we want to index a specific column. This should be similar to the typeorm way.

```
  @FieldMetadata({
    type: FieldMetadataType.TEXT,
    label: 'Handle',
    description: 'Handle',
    icon: 'IconAt',
  })
  @Index()
  handle: string;
```

```
@IsSystem()
@Index(['handle', 'visibility'])
export class MessageChannelObjectMetadata extends BaseObjectMetadata {
```
Note that for composite index, the order is important.

## Technical inputs

TBD

**Comment by charlesBochet** [comment]
Looks good to me :)

**Comment by FelixMalfait** [comment]
If unique is field-level it could be implemented like the NOT NULL constraint ; if it's multi-column then it's similar to this table-level Index implementation indeed. Not sure which one is more of a priority!

In the future there is also CHECK constraints (e.g. price > 0) which can also be implemented at the column-level as well as the field level.

Feels like this issue won't be a simple task though!?
We'd need `indexMetdata` and `indexFieldsMetadata` tables?
And then `constraintMetadata` and `constraintFieldsMetadata`?
(to keep track and cascade deletion of field to constraint, etc. as you mentioned it @Weiko)

**Comment by charlesBochet** [comment]
@FelixMalfait This time we were thinking about a JsonB column on fieldMetadata and objectMetadata! As there is no need to batch query this data or to do advanced filtering on it, it should only be used when we read a specific fieldMedata on specific objectMetadata

We will add a rule to our workspace:health command to check that the format is correct

**Comment by FelixMalfait** [comment]
@Weiko when you work on this could you consider an option to customize the type of index and eventually pass params?

As you know the user-facing search is really bad today and I have a feeling this work on index could drastically improve it.
We cannot use B-tree indexes because that works with LIKE 'search_tem%' but wouldn't work with  '%search_tem%'.
Instead we'll have to use a GIN index.
I'm not sure yet if we will use `pg_tgrm` or `ts_vector` yet,  but the queries would look similar:
`CREATE INDEX ON Notes USING GIN (to_tsvector('english', title));`
`CREATE INDEX ON Notes USING GIN (title gin_trgm_ops);`

**Comment by Weiko** [comment]
Sure, I had something like this in mind
```
export enum IndexType {
  BTREE = 'BTREE',
  HASH = 'HASH',
  GIN = 'GIN',
}

export type IndexMetadata = {
  name: string;
  columns: string[];
  type: IndexType;
  isUnique: boolean;
};

export class ObjectMetadataEntity implements ObjectMetadataInterface {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ nullable: true, type: 'jsonb' })
  indices: IndexMetadata[];
```

That will be something else to keep up to date when we migrate columns (for example the jsonb config shouldn't refer to a dead index) but we don't have much choice that storing it on the object-metadata because of composite indices I believe 🤔

**Comment by FelixMalfait** [comment]
Cool! I guess the only issue is you're losing one info here? `to_tsvector('title')`  vs `title` column
(could also be an index on lowercase(column) etc.)

For `isUnique` I personally don't feel like it belongs here since an index isn't a constraint. For me that would be a different column dedicated to constraints (I know we said it was maybe related and we should keep it in mind but now I feel like it still deserves a separate issue to be created and its dedicated column)

**Comment by Weiko** [comment]
>Cool! I guess the only issue is you're losing one info here? to_tsvector('title') vs title column (could also be an index on lowercase(column) etc.)

Ah yes I missed that, how will this work for custom objects? I feel like this will be quite complex to allow such flexibility? 
If we want to expose this then yes we'll probably need to open a bit the options like this and create a type to enforce certain functions we can apply, though I'm not sure it's the right way to do it.
```
export enum IndexType {
  BTREE = 'BTREE',
  HASH = 'HASH',
  GIN = 'GIN',
}

export type IndexColumn = {
  name: string; // (fieldMetadataId?)
  fctToApply: IndexColumnFctToApply
}

export type IndexMetadata = {
  name: string;
  columns: IndexColumn[];
  type: IndexType;
  isUnique: boolean;
};

export class ObjectMetadataEntity implements ObjectMetadataInterface {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ nullable: true, type: 'jsonb' })
  indices: IndexMetadata[];
```
If fctToApply is only for standard objects I guess we can simplify a bit, I'll need to put more thought on this 🤔 


> For `isUnique` I personally don't feel like it belongs here since an index isn't a constraint.
In the case of uniqueness, if you ask postgresql to create a unique constraint it will create a unique index under the hood and will use that to enforce uniqueness so I thought it would still make sense to be there. 
Since I don't see major difference between both, I guess we can also argue and say that a constraint is more declarative and we also want to open constraint to more things than "unique" so I'm fine with both!

**Comment by FelixMalfait** [comment]
> how will this work for custom objects

Yes I don't think this is something we would enable user to do in the UI. This is something we'd not for standard objects only or for default field of custom objects.

>   fctToApply: IndexColumnFctToApply
I feel like this is still a bit too restrictive because we'll want to create indexes like:
`CREATE INDEX people_names ON people ((first_name || ' ' || last_name));`
Also the `gin_trgm_ops` is a different concept that a fct modifier called "operator class".
So it could be:
```
export type IndexMetadata = {
  name: string;
  columns: IndexColumn[];
  type: IndexType;
  expression?: string
  operatorClass?: string 
};
````

With `expression: "first_name || ' ' || last_name"`  - which gives us more flexibility for standard objects to create better search.

Honestly I'm not sure `operatorClass` is useful because it's used rarely and we're more likely to go with `ts_vector`. Probably we can ignore this one for now and just have expression!

> In the case of uniqueness, if you ask postgresql to create a unique constraint it will create a unique index under the hood and will use that to enforce uniqueness so I thought it would still make sense to be there.

Oh good to know! I'd still vote to classify in in the constraint category

**Comment by charlesBochet** [comment]
@Weiko Agree, I would also put the Unique one in constraint even if postgres is creating an index under the hood
