### ISSUE TITLE
Own Database

### ISSUE THREAD

**Issue by kodermax** [twentyhq/twenty#3790]
I propose adding a feature that allows clients to connect their own database, enabling them to store data on their own server.

**Comment by charlesBochet** [comment]
Hi @kodermax, do you mean on the cloud version on app.twenty.com or for self hosting?

**Comment by kodermax** [comment]
Yes, I meant the cloud version.
Some advantages of this approach include:
1. Customization: Users can use their own database instance with specific configurations and settings that suit their needs.
2. Data Control: Users have full control over their data and can manage it directly within their own database.
3. Security: Users can ensure the security of their data by maintaining control over access permissions and encryption settings.
4. Performance: Using a dedicated database instance can potentially improve performance compared to a shared database used by multiple users.
5. Compliance: Users may have specific compliance requirements that can be met by using their own database instance.

By allowing users to connect their own database instance, you provide them with flexibility, control, and customization options, enhancing the overall user experience of the service.

**Comment by charlesBochet** [comment]
@kodermax We plan to allow that through what we call Remote Objects. I think it should match what you describe above, at least partially.

Right now on Twenty, you have Standard Object and Custom Objects. 
- Standard Objects are objects that come with Twenty and that already have pre-defined fields and business logic. You can enable them, disable them, modify their fields
- Custom Objects are object that you can create to model your own business. You can add custom fields to them

Both will be stored in Twenty database on the cloud version and we don't plan to allow to store them in your own database. If you have specific requirement (security, performance, compliance), we could work together to get it done but this won't be part of the base offering. Note that Twenty is technically capable of storing workspace postgres schema in different databases but we tend to mutualize and optimize resources (including database) to create a cost effective (and environment friendly) architecture. If you really want to have the full control over all your data and you also have the technical skills to manage your production database, I recommend actually self-hosting : you'll have even more control and you won't have to pay for any extra service.

That's being said, we also believe that being able to bring your own data into Twenty is super important and keeping the control is crucial. That's why we are introducing Remote Objects. They enable an hybrid model where your data can stay in your own systems and Twenty can leverage it to fuel your Twenty workspace on the cloud.

Remote objects will be object that come from "Integrations". An integration can be Postgres, MySQL, Stripe, ... Integrations can provide many things including providing remote table. 

Let's take the Postgres example and let's say you have an existing production database with your own customer data
<img width="817" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/5c735953-e7c2-42d7-bd2c-4953b54c1419">

You could setup a remote database, browse the table you want Twenty to have access to:
<img width="817" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/e79b554e-7b33-4dfa-80ed-8defcf09795b">

Once you activate a table, this will create a Remote Object in Twenty that you can use in Twenty (display Table, Kanban, create relations with other tables...)
<img width="923" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/f8898d16-fdb6-42e3-a1a5-52b64bd1619d">

You can see a bit more about what we have in mind here: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5639-59008&mode=design

**Comment by kodermax** [comment]
@charlesBochet Thank you for your detailed answer. The proposed solution is very interesting and would be useful.
