### ISSUE TITLE
Improve Storybook DateFieldInput to 

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#3797]
## Scope & Context

Every day, chromatic tests (based on storybook) are reporting diff on DateFieldInput component
<img width="1512" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/2b7bd05f-089b-4089-9b05-411a25d1d1d7">

## Technical inputs

I believe the date that is used in the DateFieldInput.stories.ts is today. It should be **fixed** to a specific date.
You can run stories using:
- `yarn nx storybook:modules:dev twenty-front`

**Comment by AbuHafsa** [comment]
Hi, I wanted to fix this issue as I thought it was quite easy. Still, I realize it is not so simple because the recoil state is not updated when setting the value through `DateFieldValueSetterEffect`.
https://github.com/twentyhq/twenty/blob/a15128df36f84e2c43deedbdc70e7efa024ebbad/packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/__stories__/DateFieldInput.stories.tsx#L13-L21

So the hook `useDateTimeField` on the component expects to use `fieldValue` but that is always `undefined`. 
https://github.com/twentyhq/twenty/blob/a15128df36f84e2c43deedbdc70e7efa024ebbad/packages/twenty-front/src/modules/object-record/record-field/meta-types/input/components/DateFieldInput.tsx#L54-L66. 

 Therefore, simply changing `formattedDate` to a specific date on the story is not the complete solution and I have personally not worked with recoil before.
