### ISSUE TITLE
Activity generated createdAt and updatedAt are wrong

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#3822]
## Bug Description

On activity creation, createdAt and updatedAt are wrong, we should check how it is created and if we have a timezone problem.

**Comment by lucasbordeau** [comment]
@charlesBochet @Weiko This should be fixed by the timestamptz refactor, we should check and update the related issues.

**Comment by Weiko** [comment]
@lucasbordeau yes, I think we can close this issue! All dates should have been updated except for deletedAt because they don't have a fieldMetadata so it was tricky to update them. DeleteAt is not used yet (until we have soft delete implemented) so it should not have any impact.
I think we can close this issue
