### ISSUE TITLE
Wrong webhook URL causes app crashes

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4021]
Related to #4018

Even if we add validation on the URL, webhooks should be dispatched asynchronously and the core request probably shouldn't fail if the webhook URL is wrong.

I entered a bad webhook URL and I'm forced to restart the server everytime I update an object because it triggers webhooks

**Comment by charlesBochet** [comment]
@FelixMalfait webhooks are dispatched asynchornously in production, are you in "sync" mode locally?

Agree that if a webhooks fail because the URL is not responding it should not trigger an exception.

From an eng perspective that the webhook system is working: 
- the try catch should be restricted to the webhook URL call. All other exceptions in the webhook systems should trigger exceptions in Sentry.
- in the future, it would be great to have some tests webhook to monitor that the webhook system is up

From a user perpsective, do we want the user to be warned that is webhook URL is not healthy?

**Comment by FelixMalfait** [comment]
@FelixMalfait yes I'm in sync mode, agree it was not well expressed. I meant that even in sync mode it shouldn't break the current request. Agree alerting about unhealthy webhooks seems low prio, we can do that once we have a system for workspace logs but working on it before would be premature!
