### ISSUE TITLE
If company.domainName is empty we shouldn't try to load a favicon

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4135]
Saw a fun bug this morning.
The website was trying to load https://github.com/twentyhq/favicon/blob/main/README.md

<img width="243" alt="Screenshot 2024-02-22 at 15 31 50" src="https://github.com/twentyhq/twenty/assets/6399865/044435db-1eaf-4d4c-9e61-4aec86c2566e">

The reason was that https://favicon.twenty.com redirects to https://github.com/twentyhq/favicon/blob/main/README.md

When there is no domain name on a company that's created we should try to load a remote icon at all / we shouldn't do a request to https://favicon.twenty.com .

**Comment by jorgesisco** [comment]
Hello Felix, I am interested in fixing this bug, I am trying to locate the issue and I can't seem to replicate it.

<img width="473" alt="Screenshot 2024-02-23 at 08 53 29" src="https://github.com/twentyhq/twenty/assets/61971454/7517022d-6447-4302-9080-6ba2ad36a189">

Can you tell me where this is happening? in all the pages I see the company, I see an icon with the 1st letter of the company name, since there is no Domain Name.

**Comment by sohalkumar** [comment]
hi @FelixMalfait 

> When there is no domain name on a company that's created we should try to load a remote icon at all / we shouldn't do a request to https://favicon.twenty.com .

The `getLogoUrlFromDomainName` always returns a URL string even if the company.domainName given to it is empty. The return statement is -
`return `https://favicon.twenty.com/${sanitizedDomain}`;`
therefore even if the `sanitizedDomain` (sanitized company.domainName) turns out to be empty, the final URL is returned as undefined.

`return sanitizedDomain ? `https://favicon.twenty.com/${sanitizedDomain}` : undefined;`
Changing the return statement like so seems to work and the request is not made.

**Comment by FelixMalfait** [comment]
@sohalkumar not tested but sounds like a good resolution path! Could you please raise a PR? Thanks

**Comment by sohalkumar** [comment]
@FelixMalfait sure I'll raise a PR right now. 
Thanks :D

**Comment by sohalkumar** [comment]
Hi @FelixMalfait.
Please review the PR.
Thanks
