### ISSUE TITLE
Introduce X-Schema-Version header

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4479]
## Context
We've seen occasional errors in the following scenario:
- user has a tab open where he modifies the schema
- user has a second tab open where he's using the app (e.g. loading lists of companies)

This causes unwanted errors because the frontend can ask for columns/objects that don't exist anymore.

## Resolution
We need to introduce an optional `X-Schema-Version` head which we will use to detect errors related to the schema discrepancy and return a user-friendly message to ask them to refresh.

- Return `workspaceCacheVersion.version` when we call the /metadata endpoint during the initial workspace load. 
- Make sure all subsequent requests to the /graphql endpoint pass this schema in a `X-Schema-Version` header
- Add a try/catch on backend to swallow errors if the Schema Version (probably in queryRunner?)

**Comment by rostaklein** [comment]
I tried to solve this via https://github.com/twentyhq/twenty/pull/4563 but im kinda helpless now, ill appreciate any help 🙏

**Comment by magrinj** [comment]
Hey @rostaklein,
Thanks a lot for your PR !
For the error you're trying to handle you should take a look inside the following files:
https://github.com/twentyhq/twenty/blob/9f6c578a46d768af4cd1fbdae5c7dda7036da7ec/packages/twenty-server/src/engine-graphql-config/graphql-config.service.ts#L160
The error might happen during schema construction instead of schema running, feel free to ping me on discord if needed !
