### ISSUE TITLE
Default Display of Company Field in Opportunities Object

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4484]
# Current Behavior

In Opportunities, the Company relation field is not visible by default. (When creating the workspace)

![CleanShot 2024-03-14 at 16 50 28@2x](https://github.com/twentyhq/twenty/assets/19412894/73ad2bc0-3641-4074-a1d7-01247c9b5e55)

# Desired Behavior

1. Display the company field type **by default** on the `Opportunity` object

![CleanShot 2024-03-14 at 16 51 42@2x](https://github.com/twentyhq/twenty/assets/19412894/71e9d596-b4e8-4f9d-ae30-41dc5e55e8b9)

**Comment by RamK777-stack** [comment]
Is that company field type editable ? like point of contact field ?

**Comment by Bonapara** [comment]
> @Bonapara Is that company field type editable ? like point of contact field ?

Yes, @RamK777-stack! It already exists but is not displayed by default.

**Comment by RamK777-stack** [comment]
We are currently receiving an array called 'viewFields' from the server, which contains only four items.

<img width="624" alt="image" src="https://github.com/twentyhq/twenty/assets/69167444/52f1bb34-f475-4683-9205-01b5dc2ceaf4">

Upon examining the server code, I'm uncertain where to make the necessary changes in order to include the 'Company' field. Could someone please assist me with this? 

@Bonapara

**Comment by Bonapara** [comment]
@RamK777-stack, I may not be the best person to assist you. You could try asking on our Discord instead!

**Comment by DevanandGowda** [comment]
@Bonapara could you assign this issue to me? I have started working on it. Thanks!

**Comment by Bonapara** [comment]
Sure @DevanandGowda, thanks for contributing!
