### ISSUE TITLE
'+' and 'Customize fields' not displayed in Table View

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#4576]
# Current behavior

When all fields are displayed in a table, the "+" icon button is not displayed

![CleanShot 2024-03-20 at 10 08 39](https://github.com/twentyhq/twenty/assets/19412894/e9602d16-ebe5-4249-aca0-8398f0249891)

# Desired Behavior

Show a "+" button with a "Customize fields" button that redirects to the good Settings page:

1. "+" icon button
![CleanShot 2024-03-20 at 10 11 20](https://github.com/twentyhq/twenty/assets/19412894/8a49ccff-257f-44a1-8bf4-71de48d84721)

2. "Customize fields" button
![CleanShot 2024-03-20 at 10 09 51](https://github.com/twentyhq/twenty/assets/19412894/112a5677-c121-4e11-b421-7521dd7e3292)

**Comment by bottlewook** [comment]
I think I can do this, assign to me!

**Comment by Bonapara** [comment]
Sure, thanks @bottlewook!

**Comment by bottlewook** [comment]
@Bonapara 
I see the + button in the companies and opportunities windows, but I don't see the + button in the people table. You want me to fix it so that the + button is visible in the people table as well?

<img width="1440" alt="스크린샷 2024-03-21 오전 11 34 25" src="https://github.com/twentyhq/twenty/assets/103362820/c454cba3-b3c0-43ea-bd74-d52364d89180">

<img width="1440" alt="스크린샷 2024-03-21 오전 11 34 35" src="https://github.com/twentyhq/twenty/assets/103362820/59fd2efc-4f8b-43cb-a7d5-c68054a12179">

<img width="1440" alt="스크린샷 2024-03-21 오전 11 34 52" src="https://github.com/twentyhq/twenty/assets/103362820/a4a76fa9-ebf1-4b87-877b-18f60367351f">

**Comment by Bonapara** [comment]
Hi @bottlewook! The `+` should appear on every Object `Table View` last column indeed, **even when all fields are displayed.**

**Comment by Bonapara** [comment]
@bottlewook, not sure to understand what you mean!

> So the plus button should be visible even if there are more than 13 columns?
Yes, if the user scrolls to the max right. Why do you say specifically 13?

> That would make the head value of the col invisible, is that okay?
What do you mean? Why would it hide anything?

**Comment by FelixMalfait** [comment]
(+) is displayed for me ?

But it's ugly we should fix the style:

<img width="255" alt="Screenshot 2024-04-15 at 18 43 51" src="https://github.com/twentyhq/twenty/assets/6399865/dabc0fa5-0656-4555-8f2e-832c8f1d643a">

**Comment by FelixMalfait** [comment]
I'll create an issue
