### ISSUE TITLE
Environment variable typing is incorrect leading to boolean misinterpretation

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#4628]
## Bug Description

I'll take the example of `CALENDAR_PROVIDER_GOOGLE_ENABLED` environment variable.
Let's set it to `CALENDAR_PROVIDER_GOOGLE_ENABLED=false` in our `.env`

It's registered in environment-variables.ts by:
```
  @CastToBoolean()
  @IsBoolean()
  CALENDAR_PROVIDER_GOOGLE_ENABLED: boolean = false;
```

However, when we get it through environmentService, we get it as a `string`:
![image](https://github.com/twentyhq/twenty/assets/12035771/82300403-4d1f-4584-865c-7a4fb6ee9908)

This leading to issue as Typescript believes it's a `boolean` an allow if (CALENDAR_PROVIDER_GOOGLE_ENABLED) which will return true even if CALENDAR_PROVIDER_GOOGLE_ENABLED=false

**Comment by charlesBochet** [comment]
I think the issue is that our @CastToBoolean is not applied when getting the env through `ConfigService` in `EnvironmentService`
```
@Injectable()
export class EnvironmentService {
  constructor(private readonly configService: ConfigService) {}

  get<T extends keyof EnvironmentVariables>(key: T): EnvironmentVariables[T] {
    console.log(key, new EnvironmentVariables()[key]); // Correctly typed
    console.log(key, this.configService.get(key)); // Incorrectly typed

    return
``` this.configService.get<EnvironmentVariables[T]>(
      key,
      new EnvironmentVariables()[key],
    );
  }
}

**Comment by charlesBochet** [comment]
Also regarding the DX, we get the error when the variable does not exist but we don't have autocompletion, I don't know if there is a nice way to get it (with a string litteral)
<img width="628" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/0fdb6d0f-36b9-4e1d-b920-7ddcdbb94295">

Here it could propose 'DEMO_WORKSPACE_IDS'

<img width="628" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/b6b1f380-7fef-426f-8744-059036932a8f">

**Comment by charlesBochet** [comment]
Another example with CastToArray not being applied:
<img width="805" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/14cef819-6421-48a0-80e9-ad4a73600339">

**Comment by FelixMalfait** [comment]
OK I did an investigation,  it's just linked to the few places where we do EnvironmentService(new ConfigService()) ; it works in other places. It was a bad idea because it doesn't do casting in this case and gives a false impression that it's done 

We could either move casting to the environment service layer or just come back to the old way and accept that there is no casting when the app isn't instantiated

<img width="557" alt="Screenshot 2024-04-05 at 17 25 38" src="https://github.com/twentyhq/twenty/assets/6399865/e78b128c-d296-4c20-9196-8398671d9282">

<img width="1177" alt="Screenshot 2024-04-05 at 17 25 58" src="https://github.com/twentyhq/twenty/assets/6399865/5feaed1f-1d3f-412e-83ee-a7e6b285fab2">
