### ISSUE TITLE
Red bar between events is flashing when opening the calendar tab

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#4692]
## Bug Description

Red bar in event is flashing when opening the calendar tab.

https://github.com/twentyhq/twenty/assets/71827178/fdad746f-61f0-47c8-a74d-8ee581459dd3

## Expected behavior

Should not flash.

**Comment by FelixMalfait** [comment]
This is now even more subtle, with a small width of a few pixels (todo: check that rebar is still properly displayed  with the full width when it's an an ongoing meeting)

It's probably because we default to true somewhere instead of defaulting to false

https://github.com/user-attachments/assets/ab88a483-a9ab-484a-97a1-f4866792d315

**Comment by FelixMalfait** [comment]
/oss.gg 350

**Comment by harjasae2001** [comment]
it should be unassigned automatically after 48h
