### ISSUE TITLE
I shouldn't be able to click on "signup" or press "enter" twice

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#4809]
During signup (and probably login), if I press "enter" twice or click twice on the button then I get this error.

We should disable the button or add a debounce (not sure what we're doing in other similar areas of the code)

<img width="942" alt="Screenshot 2024-04-04 at 15 11 30" src="https://github.com/twentyhq/twenty/assets/6399865/f0bce9f8-d293-4484-a181-245018222a4a">

**Comment by qnsi** [comment]
Hi, I looked into it and fixed in PR #4878 tested locally and this fixes it.

I know I need to sign CLA, can someone please explain how to do it? Couldn't find it in the docs. 

Also, the similar bugs are in other parts of the code (especially when pressing enter to trigger submit, the form submits multiple times)

**Comment by FelixMalfait** [comment]
Thanks @qnsi! Would you mind raising an issue for the other places in the app where you've seen this? Or fixing in your PR directly eventually?

Sorry for the slow response delay, we are a bit under water these days as we try to make progress on major features in parallel with ongoing pr review/improvements

No need to do anything for the CLA, we might want to clarify the message!

**Comment by FelixMalfait** [comment]
@qnsi closing this but would really appreciate if you find other things to fix let us know haha 😁
