### ISSUE TITLE
ScrollTop and ScrollLeft state should be componentStates to avoid side effects

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/twenty#4826]
## Scope & Context

While refactoring ScrollWrapper component, we have recently introduced two states: ScrollTop and ScrollLeft. These states should be componentState so each ScrollWrapper instance does have its own state. Otherwise they are all interacting together, creating re-renders

## How:

In `scrollLeftState` (same for `scrollTopState`)
- Rename it to scrollLeftComponentState, and use `createComponentState` instead of `createState`
- introduce useScrollStates hook that will only extractComponentState and take a scrollWrapperId as a parameter. See `useViewStates` for an example.
- replace direct import of scrollLeftState by call to useScrollStates

**Comment by Jeetch8** [comment]
I want to take on this issue. Can you please assign it to me ?

**Comment by charlesBochet** [comment]
Sure! Thank you @Jeetch8

**Comment by Jeetch8** [comment]
I have created the PR. Please check #4938

**Comment by FelixMalfait** [comment]
<img width="677" alt="Screenshot 2024-05-17 at 09 19 18" src="https://github.com/twentyhq/twenty/assets/6399865/e43a4fe1-1646-44c5-8675-75ec8d8b34bd">

**Comment by ehconitin** [comment]
is this issue still open @FelixMalfait ?
Can I work on this?

**Comment by FelixMalfait** [comment]
Of course thanks @ehconitin ; not sure if it's still up to date since it dates back to April! Let us know

**Comment by ehconitin** [comment]
Quick question to clarify the implementation.

Do we need to set up a context for scrollWrapperId? I’m thinking we’d need it to make sure it’s available across the component tree where needed.

Just to confirm:

- Should we create this context to provide `scrollWrapperId`?

- How should we make sure `ScrollWrapper` and related components are wrapped with this context so we don’t run into issues with `useAvailableScopeIdOrThrow`?


Thanks for the help!

**Comment by FelixMalfait** [comment]
I'll let @lucasbordeau answer this!

**Comment by lucasbordeau** [comment]
@ehconitin The problem with contexts is if we have nested contexts, useContext will take the closest parent context, we can't change that. 

Since this could happen with nested scrollable containers, we should maybe only rely on scrollWrapperId without using contexts, so we'll have to force passing scroll wrapper ids.

Another solution, which could be more elegant is to create a specific scroll wrapper context per scroll wrapper, for example : TableScrollWrapperContext, BoardScrollWrapperContext, etc.

This way we're sure that we're using the right context every time, it's a little bit more verbose but we shouldn't have a lot of scroll wrappers anyway.

**Comment by ehconitin** [comment]
Could you review [PR 6645](https://github.com/twentyhq/twenty/pull/6645)

**Comment by charlesBochet** [comment]
@lucasbordeau could you take a look?

**Comment by ehconitin** [comment]
@charlesBochet could you close this issue
#6645 fixed it

**Comment by charlesBochet** [comment]
You are everywhere, thank you!
