### ISSUE TITLE
Use new people displayName computed field for table filter instead of first and lastname

### ISSUE THREAD

**Issue by lucasbordeau** [twentyhq/twenty#497]
<img width="716" alt="Screenshot 2023-07-21 at 14 19 21" src="https://github.com/twentyhq/twenty/assets/6399865/d2839603-76ef-4509-bef2-d81ca43226ef">

**Comment by FelixMalfait** [comment]
@lucasbordeau is this still relevant after the refacto?

**Comment by FelixMalfait** [comment]
@charlesBochet removing "good first issue" as I don't think it's explicit enough. A beginner would need more context

**Comment by codergirl2023** [comment]
@charlesBochet @FelixMalfait  I went through the feature request, From the setup I  have come up with following design 
1. Need to create new field called "displayName" which will be computed field with value=firstname+" "+lastname in TypeORM. 1.1 Need to generate migrations
2. Modify GraphQL queries to return displayName and not include FirstName and LastName
3. Need to modify search filters to work on displayName instead of firstName and lastName

Please assign this feature request to me.

**Comment by charlesBochet** [comment]
Yes, we might need to compute it.

I think it falls into the "computeField" global effort that we haven't started yet. @codergirl2023 we will likely take a more global approach to solve this but this cannot be done before releasing the customObjects and customField which is a pre-requesite

**Comment by charlesBochet** [comment]
Closing this issue as we have introduced the FULL_NAME field type which is solving this
