### ISSUE TITLE
[Timebox] Investigate FDW failed states

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#5083]
- Check broken connection / wrong credentials
- Check relations
- Check app (show page, list, etc)

**Comment by ijreilly** [comment]
Investigation results

- broken connexion / wrong credentials triggers server errors on list page if tables have been synchronized. (this should not be the case since we could already have broken connexion cases. [An issue](https://github.com/orgs/twentyhq/projects/1/views/10?pane=issue&itemId=60719896) was created to handle that)
-  if the updated configuration connects to a db that has the same table names and table columns as the one synchronized, it keeps working
