### ISSUE TITLE
Support Select field in CSV import

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#5471]
Right now we don't support the select field in CSV import which is annoying, especially when importing opportunities/deals from another CRMs. We can only import a few field types (e.g. string, date, and soon a few composite fields).

We should allow importing CSV and ideally work on the UI to give feedback as the user is importing on whether the provided values are valid given the options accepted by the enum field.

**Comment by livingstonlarus** [comment]
Hi Felix, as a user trying to import a CSV of companies, after matching fields, I have an error while launching import:

A notification quickly shows _Response not successful: Received status code 400_ and in the page itself:

_Minified React error 185; visit [https://reactjs.org/docs/error-decoder.html?invariant=185](https://reactjs.org/docs/error-decoder.html?invariant=185) for the full message or use the non-minified dev environment for full errors and additional_

The React.dev page states for error 185:

_Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops._

But I tested with fewer records and columns and I still have this issue.

So I'm wondering if it's caused by the issue you reported here. I'm importing a CSV where some of the columns go to custom fields I added to the Companies object, which are of types Select and Multi-select.

Could it be that or is it unrelated and I should open a new issue? Thanks.

**Comment by FelixMalfait** [comment]
@livingstonlarus yes I guess it's the same problem... If you go into the network tab and look at the request response body (of your 400), you would probably see additional details. I hope we can improve this soon, we haven't planned it yet but I consider it a high priority.

**Comment by livingstonlarus** [comment]
Maybe another (minor) issue: after a successful import, I still have the _Minified React error 185_ on the main screen (but not the _code 400_ notification). Clicking the menus won't remove the message. I need to reload the app to make it go and acknowledge that the records have all been imported successfully.

<img width="570" alt="Screenshot 2024-05-21 at 15 18 31" src="https://github.com/twentyhq/twenty/assets/55496551/e772df0c-c292-4211-8a4f-af825d8b573f">

**Comment by livingstonlarus** [comment]
In relation to #5506, before I was aware that custom fields with type `select` or `multi-select` are not supported by CSV import, I wondered how options not declared in the field would be treated. I had dozens of options to insert. So I was hoping that the import would *create* automatically the options that were missing. That would be a cool feature. Maybe warn when importing that some options does not exist for said field and will be created. Otherwise, you can have a complex UI to create and match options directly in the import process, like Pipedrive is doing. But that's on another level.

**Comment by FelixMalfait** [comment]
We've improved CSV import, it's not perfect yet but I think we can close this

**Comment by thinkbig1979** [comment]
Hi all, this is still broken. If I create an entity with multi select fields, and export it from Twenty, then try to re-import the file I just exported (after deleting the existing data from the table), it simply does not recognise the multi-select entries.

**Comment by FelixMalfait** [comment]
Hey @thinkbig1979  - I think this is tracked here #5793 (multi-select is - unfortunately - a different implementation than select)
