### ISSUE TITLE
Know which fields are optional in API doc

### ISSUE THREAD

**Issue by waynehamadi** [twentyhq/twenty#5574]
We don't know what's optional and what's not right now. And also there is no example I can quickly copy paste
Example here.
https://docs.twenty.com/rest-api/metadata#/operations/createOneRelation
<img width="1037" alt="Screenshot 2024-05-25 at 5 48 44 PM" src="https://github.com/twentyhq/twenty/assets/9652976/5012cfb8-be7e-4c95-8746-3e8412592c61">

**Comment by FelixMalfait** [comment]
We have very flexible requirements and so far the fields in the body are not required. 

When a field is required it's usually in the path and marked as required in the doc

<img width="609" alt="Screenshot 2024-06-11 at 15 18 27" src="https://github.com/twentyhq/twenty/assets/6399865/9086a4d0-73d7-479f-aaa4-5f81d9739506">

Probably later we'll enable required fields in the UI and then we should reflect this in the API. Since we do a lot of auto-save we took a more Notion-like approach for now with less constraints initially
