### ISSUE TITLE
Once you click on a boolean field, you can't unset it.

### ISSUE THREAD

**Issue by waynehamadi** [twentyhq/twenty#5579]
## Bug Description

Once you click on a boolean field, you can't unset it. It has to be either true or false.

But in my case, I don't know what the value is. I want it to remain null

**Example:** 
https://www.loom.com/share/088150a795fc44eeb98641cab6562d2c

**Comment by FelixMalfait** [comment]
See https://github.com/twentyhq/twenty/issues/4438

We ended up going with a default value (which is seems you don't like) as it made the ux easier. Otherwise we'd have to introduce some sort of dropdown I guess which isn't as cool as the one-click toggle ux. In your case maybe you want a select field? 

I'm surprise you don't have a default value though! In your settings I guess you had a default value for that field? maybe it was forced reset through api? I wonder if we have a bug where default value wouldn't always be properly applied?

**Comment by waynehamadi** [comment]
Sometimes you don't know the value.
I am starting to think that I should represent a nullable boolean as a string. It might simplify things.
Because I have the same problem on windmill too: encountering issues with nullable booleans.

**Comment by waynehamadi** [comment]
@FelixMalfait it's weird that something you can do through the API (aka set a boolean field to null) literally cannot be done through the twenty app.
That's all I am asking for: a way to do it.

**Comment by FelixMalfait** [comment]
Why don't you like the Select field? That's what I would go with, you can set 3 options

**Comment by waynehamadi** [comment]
@FelixMalfait  I see. I was just hoping the boolean field would handle it. It's common to have a value for "I don't know what the value is".
The interesting thing is that if you don't populate the boolean you get this "N/A" state, but there is no way to get it back through the UI. It has to be through API call.
