### ISSUE TITLE
Add Skeleton Loading to detail page tabs

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5656]
# Current Behavior

The empty state is displayed on page rendering, even if content is going to load afterward. This causes the page to flash.

https://github.com/twentyhq/twenty/assets/19412894/a8f59389-2b13-4003-9739-7d739ba48f3d

# Desired Behavior

Introduce a light skeleton loader that mimics the first skeleton box of the timeline while waiting for content. The skeleton box should match the first one in the timeline tab exactly, ensuring it always appears in the same place when navigating quickly between tabs.

If there is no content to load, make the empty state fade in with` a 150ms animation`.

https://github.com/twentyhq/twenty/assets/19412894/7db0fc28-88ac-4f6e-92dd-f81d9bf0bc65

# Figma

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=32007-44499&t=P12gjv5ZcZ9hChR8-11

**Comment by chilled-farmer** [comment]
Can you assign this to me @Bonapara

**Comment by its-id** [comment]
Hi @Bonapara, was looking into this issue. It looks like the glitch is happening due to delay in fetching of items and thus leading to first showing the default empty placeholder then the content.

The effect which is asked, if you can refer me to a similar effect implementation done in past. A possible soln which seems to be implemented here is integrating another 'loading' boolean to be fetched from the `useRecoilValue` and based on its check we can confirm and perform a clean transition.

Would really use some confirmation here. @lucasbordeau

**Comment by Bonapara** [comment]
@lucasbordeau Maybe an idea for @its-id? We implemented a similar skeleton loading on the `account` page, but I'm not sure if it's comparable.

**Comment by lucasbordeau** [comment]
This issue can get pretty hard to solve, we should assign it to the core team. The activity part is too complex for now, it is planned to be simplified once we get our new ORM.

**Comment by Bonapara** [comment]
👌 Can you handle it for the next sprint then, @lucasbordeau?
