### ISSUE TITLE
Automatic Column detection

### ISSUE THREAD

**Issue by vasnt** [twentyhq/twenty#5885]
This feature may need some kind of AI/logics. 

1)
Imagine there is a table having 20+ (more) columns.
While adding a new row item in this table, it is very uncomfortable to move to specific column & fill in the data. 
 It is definately useful for users, if COLUMN is automatically selected based on data entered. i.e. if someone types 21-5-2000 it will be added directly transferred into date column. If some one types "Tokyo" it will be added in Location/City column.

This will drastically help to users to fill in the data in a smoother way without breaking typing flow/manually moving cursor to specific column. 

This will feel me like i am typing in Obsidian.

Or the gap between markdown/notes & tables shall be bridged.

2) Autocompletion shall be also useful

**Comment by FelixMalfait** [comment]
I like the suggestion, I feel like this is a very interesting idea that I haven't seen implemented anywhere else. But I'm going to close this for now because we are still focused on getting the basics right before we can afford to explore a creative UI like this one :)). Backlog is focused on work that we will tackle in the next 6 months. We will keep it in mind long-term though.
