### ISSUE TITLE
Menu Items Order Should Match Table Column Headers Order

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5960]
# Current Behavior

`Filter` and `Sort` menu items are displayed in alphabetical order (1)

![CleanShot 2024-06-19 at 15 20 43](https://github.com/twentyhq/twenty/assets/19412894/5c3ed24d-f174-4e9a-81f3-dafdcf0d2207)

# Desired Behavior

**Visible** `Filter` and `Sort` menu items (1) should be displayed in the same order as the column headers in the table (2)(A).

**Hidden** columns should be displayed below - in a different section - by alphabetical order (B). There should be a separator between the two sections (C)

![CleanShot 2024-06-19 at 16 47 24](https://github.com/twentyhq/twenty/assets/19412894/89965cde-d88a-41a5-838e-fec82f47c01a)

**Comment by FelixMalfait** [comment]
You can filter/sort on fields that aren't visible on the table. That might get a bit confusing? The ones that are not visible should then be sorted alphabetically?

I would love for us to have sort option by clicking on the  the field directly. I think @Kanav-Arora had started working on it but it wasn't merged because it was more work than he initially expected

**Comment by Bonapara** [comment]
> You can filter/sort on fields that aren't visible on the table. That might get a bit confusing? The ones that are not visible should then be sorted alphabetically?

Issue description updated: Let's introduce a second section for non visible fields to make things clear

**Comment by Nabhag8848** [comment]
@Bonapara I would like to take this, started working do assign.
