### ISSUE TITLE
Change Email Sync Status Display from "Complete" to "Active"

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#5961]
# Current Behavior

The chip on the Email settings displays "Complete" when emails are synced.

![image](https://github.com/twentyhq/twenty/assets/19412894/c03a2532-50ad-4992-805b-33a2fe0329ee)

# Desired Behavior

It should display "Active" to better indicate that future emails will be synced and that it is not just an import.

@bosiraphael

**Comment by Samaresh-Das** [comment]
Can I take this issue?

**Comment by Bonapara** [comment]
Sure @Samaresh-Das, thanks for contributing!

**Comment by charlesBochet** [comment]
@Samaresh-Das we already have two PRs on this one. Have you started any work? If not, I'll review @akarsanth one tonight

**Comment by Samaresh-Das** [comment]
@charlesBochet Sorry I was just about to tell today, I indeed started working on it but due to some hardware problems in my laptop, it was taking time. Sure you can merge the other PRs as I cannot do much until repair. I will look forward to contributing on other issues once my laptop is fixed. Sorry for the trouble.

**Comment by charlesBochet** [comment]
No worries! appreciate the interest in the project and contributing to it anyway!
