### ISSUE TITLE
Company icon isn't displayed properly

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#611]
Sometimes, when you don't write "www" at the start of the Url the icon doesn't get fetch.

For instance, writting apple.com doesn't work but www.apple.com works (it displays the logo properly)

**Comment by Bonapara** [comment]
API seems fix, to follow

**Comment by FelixMalfait** [comment]
One thing we could do is not fetch the largest icon if we don't need to (we need it on show view but not on list view).
The match rate is probably higher there, cf Apple:

<img width="1023" alt="Screenshot 2023-07-30 at 09 07 43" src="https://github.com/twentyhq/twenty/assets/6399865/7c6a615b-feea-4529-a322-cafcafe898d5">


Let's do size 57 from faviconkit instead of 144?

This should also very slightly improve loading time

**Comment by Bonapara** [comment]
Same for:
<img width="988" alt="image" src="https://github.com/twentyhq/twenty/assets/19412894/1e99cc3c-856b-4afb-b908-61083bfbf19e">

**Comment by Bonapara** [comment]
Maybe we can fetch the small one on index and the big one on the show

**Comment by FelixMalfait** [comment]
Closing as we will handle this on the Favicon repo
