### ISSUE TITLE
Alternative to Docker for Setting Up Twenty CRM on AWS Lightsail?

### ISSUE THREAD

**Issue by muzzamilshaikh** [twentyhq/twenty#6123]
Hi there,

Thank you for the detailed instructions on setting up Twenty CRM on AWS Lightsail using Docker Compose. While I appreciate the guide, I'm interested in exploring alternative methods that don't involve Docker.

My question is:

Are there any documented instructions or recommendations for setting up Twenty CRM on AWS Lightsail without using Docker?

**Comment by muzzamilshaikh** [comment]
I'm not able accept the invite

**Comment by FelixMalfait** [comment]
Hey @muzzamilshaikh I'm sorry we're still focused on improving the product right now, more than adding new self-hosting options. It should be possible to deploy it yourself with a raw "node" install like we're doing locally. But the Postgres database will be a challenge because you won't be able to use RDS as we still rely on a custom extension called pg_graphql which can't be installed on RDS. Closing for now, but hopefully one day the install will become simpler and could be done without docker!
