### ISSUE TITLE
Can't able to login 

### ISSUE THREAD

**Issue by muzzamilshaikh** [twentyhq/twenty#6170]
## Bug Description
I've deployed my twenty CRM in the AWS light sail instance after visiting that URL i tried to continue login with the default email which is "tim@apple.dev" but it failed to login the response was this "QueryFailedError" when I inspected that this is the repose below 

`response 
{
    "errors": [
        {
            "message": "QueryFailedError",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "response": "relation \"core.user\" does not exist"
            }
        }
    ],
    "data": null
}
`
I don't know what to do I'm totally new to this please help me

**Comment by aficiomaquinas** [comment]
I struggled with this myself, the problem might be that the database is not properly initialized running `yarn` and then `yarn database:init:prod` on the server container, or that you are using the incorrect schema/user.

If you are deploying with a different docker compose than the default it could be useful to further debug this if you could share your compose. In my case both selecting the wrong schema, the wrong user, simply trying to use something else than the official db docker (i wanted to use supabase), many things caused this error. 

In order to really know what is going on it would also be useful to see the server and the db logs.

**Comment by EmaX093** [comment]
![image](https://github.com/user-attachments/assets/14d1f352-13b8-426c-93d1-6f2d59f9c1de)

**Comment by georgezgeorgez** [comment]
At first I installed on a 2gb ram box and got insufficient JavaScript heap when I ran the database:reset.

I bumped to 4gb and was able to run the database:reset, but I still received the query error. It started working after I ran yarn database:unit:prod as @aficiomaquinas mentioned.

**Comment by infernix** [comment]
Had similar issues; afaict this does not work if behind a corporate proxy.
