### ISSUE TITLE
Explain Privacy of File Uploads

### ISSUE THREAD

**Issue by onavhamid** [twentyhq/twenty#6418]
## Scope & Context

After uploading a file to an opportunity, we noticed the URL to the file will open regardless of log-in status.  That was a bit surprising.  Is this a hidden link, say akin to a Google Docs "Anyone with link can open file"?

## Current behavior

Uploaded files are not protected by any authentication.  This is experienced using the Twenty.com hosted service.  And there doesn't appear to be a way to delete the files (i.e. it can be removed from the notes, but the URL still opens it)

## Expected behavior

1. When adding files, it should include an explanation of the file privacy status.  
2. Removing the file should also disable the URL and delete the file from the server.
3. Add options to change them (e.g. require being part of a team).  

Thanks in advance.

**Comment by FelixMalfait** [comment]
Hey @onavhamid sorry for the very slow reply here.

I think when you tried this we were halfway through implementing the auth token for files, so it was indeed just a "privacy by secret url" which isn't great. This has since been updated and now a short-lived token is generated, so it should be much more secure...

Thanks a lot for your feedback.
