### ISSUE TITLE
Moving a block in the RichTextEditor duplicates it

### ISSUE THREAD

**Issue by bosiraphael** [twentyhq/twenty#6564]
## Bug Description

Moving a block in the note editor duplicates it.

https://github.com/user-attachments/assets/7a0659a2-3207-4de4-bd23-98beff5100db

## Expected behavior

It should just change its position.

## Technical inputs

`packages/twenty-front/src/modules/activities/components/RichTextEditor.tsx`

**Comment by ehconitin** [comment]
Hey @bosiraphael,

It turns out it’s always behaved this way. 

https://github.com/user-attachments/assets/d62ff781-57cf-41f1-89b1-b5dff0bb2da1

I was initially worried that this [commit](https://github.com/twentyhq/twenty/commit/0c99bfbc31da8327979c6fa7a8e00b95208360e5) might have altered its behavior.

I’ll look into how to achieve the desired behavior.

Thanks!
