### ISSUE TITLE
bug(ui):  ConfirmationModal when Deleting Webhook should have a overlay in SubMenuTopBar

### ISSUE THREAD

**Issue by Nabhag8848** [twentyhq/twenty#6737]
#### Actual: 

<img width="1918" alt="Actual" src="https://github.com/user-attachments/assets/fe5177c1-bb33-402a-87e6-718c7d1c0b83">

#### Expected: 
Should be Similar to Api Key Deletion

<img width="1918" alt="Expected" src="https://github.com/user-attachments/assets/7a689832-1ee0-4670-9e5f-468c4e6a7e09">

Note: some more information ->  this also happens when delete workspace -> under **/settings/workspace**.

**Comment by ehconitin** [comment]
![image](https://github.com/user-attachments/assets/3870dac1-f18d-4fac-a534-013adc7bc4b4)

I thought that was to see the function/webhook/workspace name, that is to be entered to delete it.
but it seems like it asks to type yes while deleting webhook.
I think this should be consistent all across.
@lucasbordeau could u look into this please

**Comment by Bonapara** [comment]
Hi, thank you for raising this issue! 

Indeed, the title should be behind the overlay. But the overlay should be lighter so it's easier to read what's under the content.

We should use "Overlay Secondary" instead of "Overlay primary" there

![CleanShot 2024-08-28 at 17 32 23](https://github.com/user-attachments/assets/901d9423-6c1d-4075-b6d8-9f4e248372bc)

**Comment by charlesBochet** [comment]
@Bonapara should the whole overlay be lighter or just on top of the Breadcrumb bar?

**Comment by Bonapara** [comment]
The whole overlay. (That should cover the entire screen, leaving no part uncovered.)

**Comment by BOHEUS** [comment]
@FelixMalfait this issue can be closed as changes are merged

**Comment by FelixMalfait** [comment]
Thanks @BOHEUS
