### ISSUE TITLE
New standard fields for Opportunities

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#678]
Add: 
- Opportunity owner
- Close confidence
- Point of contact

**Update all the spacing and size to match the Figma** 

See Figma: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=4228-58301&mode=dev

**Comment by Bonapara** [comment]
(In that order)

**Comment by FelixMalfait** [comment]
Isn't that duplicated from what we have at the company level? Shouldn't we surface the company account owner on the opportunity card as a first step? I feel like in most cases it would be the same owner for the opportunity and the company (this might not hold true as we grow and the software is used by larger cos but I feel is true for near-term user base)

Should POC be at the company-level instead of opportunity level too?

**Comment by Bonapara** [comment]
I think it's ok to have both (Company owner & opportunity owner) with the ability to hide opportunity owner soon (next week?)

**Comment by FelixMalfait** [comment]
Introducing those fields now feels a bit premature to me. Can we prioritize displaying and allowing editing the company owner and point of contact field on the opportunity card first and get feedback from there? Since it's a one-to-many relation it's easier to start from one (company) and move to many (opportunities) than the opposite (going from many to one forces us to do things like getting the first element which is not pretty).

**Comment by emilienchvt** [comment]
IMO the experience of editing the owner from the opportunity card is misleading: as a user I would not expect to see all the cards from the same company being updated when I set an owner on a single one (if I understood the proposal correctly).
Hence I'd say we should chose between:
- Enabling users to set an owner per opportunity (with the complexity highlighted by @FelixMalfait )
- Showing the company owner on the card in a non-editable way (less empowering for users though)

WDYT @FelixMalfait @Bonapara ?

**Comment by FelixMalfait** [comment]
It's a good point. The thing is that it will be very rare to have 2 cards for the same company in the same board. It feels a bit wrong that we need to optimize design for that use-case. Even two cards for the same company in two different boards will be an exception, not the common use case.

I'm okay for read-only, this is not optimal but I feel like it's better than introducing the complexity of duplicated fields / field-hierarchy.
At Airbnb, account owner in Salesforce was a more complex field (could hold multiple account owners / a team of account owners). So even if we keep a single field, it will hold more complexity soon

**Comment by emilienchvt** [comment]
## Conclusion

We'll do the following:
- No company owner on the opportunity card, this may come later when we are able to filter on the progressable type's fields (eg `Company` here)
- We add a Point of Contact at the opportunity level and make it available as a board filters.

@FelixMalfait @Bonapara I'll proceed to implem
