### ISSUE TITLE
"Created by" flash upon click

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#6807]
# Current Behavior

**Created by** values disappear on click

https://github.com/user-attachments/assets/fa0ea4d1-df15-448d-9175-4dbb09e8e365

# Desired Behavior

Nothing should happen on click

**Comment by RobertoSimonini1** [comment]
@Bonapara I would like to fix this issue

**Comment by Bonapara** [comment]
Sure @RobertoSimonini1, thanks for contributing!

**Comment by RobertoSimonini1** [comment]
@Bonapara I couldn't reproduce the bug, I noticed it happens when I click on the header Created By and then Filter

**Comment by charlesBochet** [comment]
I could reproduce, it only happens when a filter on Created By has been applied

**Comment by Patriksafar** [comment]
Find out it might be caused by `RecordTableCellBaseContainer.tsx` component and relevant to `openTableCell` function. Removing this function fixed issue for me:

https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/object-record/record-table/record-table-cell/components/RecordTableCellBaseContainer.tsx#L70

**Comment by charlesBochet** [comment]
Thanks for investigating @Patriksafar, I think we should dig deeper to find the root cause here! 
1) we should not trigger openTableCell for a readOnly field
2) why is openTableCell creating this behavior?
