### ISSUE TITLE
🧮 Aggregate queries

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#6868]
Our GraphQL API should support aggregate queries on findMany queries.

We already have `totalCount` so we can take inspiration from that.
But it's significantly more challenging because the aggregated fields name are dynamic and depend on the object names themselves. Here's how it could look like:

```
query {
   companies {
    edges {
      node {
        id
        domainName {
          primaryLinkLabel
        }
        people {
          totalCount
          maxCreatedAt
        }
      }
    }
    totalCount
    maxCreatedAt
  }
}
```

We'll need to add: `min`, `max`, `avg`, `sum`, `countDistinct`

**Comment by FelixMalfait** [comment]
Default aggregations available for all fields:
<img width="464" alt="Screenshot 2024-09-03 at 13 04 26" src="https://github.com/user-attachments/assets/d3cabbe0-9b71-468d-a473-175efe2b2874">
<img width="448" alt="Screenshot 2024-09-03 at 13 04 38" src="https://github.com/user-attachments/assets/2bd73e72-fef2-4f87-b26a-807ad076e2c6">

For date fields:
<img width="454" alt="Screenshot 2024-09-03 at 13 05 31" src="https://github.com/user-attachments/assets/9442b663-d930-46ff-9882-a4271d3b58a4">

For numeric fields:
<img width="247" alt="Screenshot 2024-09-03 at 13 06 21" src="https://github.com/user-attachments/assets/35c7a50f-bdbd-40f7-8dcb-060d517ddb47">

**Comment by Bonapara** [comment]
https://github.com/user-attachments/assets/5f7fb0db-0971-4a5d-b5be-d9a2f628df55

**Comment by ijreilly** [comment]
> CleanShot.2024-09-19.at.13.57.53.mp4

@Bonapara do we have further designs ?

**Comment by Bonapara** [comment]
Still needs something @ijreilly?

**Comment by ijreilly** [comment]
no all good for now after our talk ! @Bonapara

**Comment by ijreilly** [comment]
Next steps:

1. Expose current available aggregate operations (MAX, MIN, AVG, SUM)  on table views
2. Same for kanban views 
3. Use "count" from aggregate operations instead of "totalCount"

For 1.: 
1. (FE) Add "calculate" at the bottom of all compatible fields in table views 
2. (FE/BE) Update viewField's aggregateOperation accordingly to store the information and be able to always show the aggregate required even after refresh. 
3. (FE) The aggregate operation is the same type (ex: MAX) for all view groups, but with the information corresponding to the filtered records belonging to the viewgroup.
4. (FE) Trigger refresh of the aggregate operation query after any update on the table as we cannot do optimistic rendering for aggregate queries

For 2.:
1. Store information in new kanbanAggregateOperation column on view table

**Comment by ijreilly** [comment]
For information - two minor features have been left aside for now:

- Aggregate operations on relations (we only expose Count all for now)
- End of page stickiness of aggregate bar on view groups
