### ISSUE TITLE
Date picker clips through navigation bar in mobile

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7014]
## Bug Description

- Go to people in companies/people, Choose any Last update/Creation date and scroll to end of the page.
- this only happens when scrolled to either the end of page or with respect to the section

## Current Behaviour
<img width="441" alt="Screenshot 2024-09-13 at 12 59 50 AM" src="https://github.com/user-attachments/assets/31535594-f274-4a12-a420-2facc4da52bf">
<img width="407" alt="Screenshot 2024-09-13 at 1 00 38 AM" src="https://github.com/user-attachments/assets/e7f1d569-9fd6-40f6-b7a3-3a1c23e195b1">

## Expected behavior

It should automatically reposition it's orientation to top just like Phone number field.
<img width="411" alt="Screenshot 2024-09-13 at 1 01 55 AM" src="https://github.com/user-attachments/assets/dbeecb41-d799-4eb3-85cf-d0723f8f019b">

**Comment by lawlesx** [comment]
I am taking up this issue.
Please assign me.

**Comment by sephialaureenciaa** [comment]
Hi, Can I contribute to this?

**Comment by HKS07** [comment]
Hey @Bonapara and @harshit078 can I work on this. 

I have already done some changes to the UI as shown in video for both full screen and mobile screen.

Full Screen

https://github.com/user-attachments/assets/996729d9-3231-426c-a0ea-5b1ea26b726a

Mobile Screen

https://github.com/user-attachments/assets/5dcd775b-2656-409f-8dd9-2bcc6ea87c1e

Please tell me if any changes are needed.

**Comment by Bonapara** [comment]
Thanks @HKS07. Is the calendar still cropped on mobile? At what point does it start getting cropped?

**Comment by HKS07** [comment]
It is starting cropped around 420 px [width].

![image](https://github.com/user-attachments/assets/27406bf9-115b-43c1-94be-e3396ad47260)

Shouldn't there be media query used to make is compatible for small size devices? If yes, then what width should I target?

**Comment by Bonapara** [comment]
I think it should work up to 360px. We should aim for the same desired behavior as in this issue: https://github.com/twentyhq/twenty/issues/7216

I also noticed an overflow issue with the navbar in your screenshot, @harshit078:

![CleanShot 2024-09-23 at 18 45 46](https://github.com/user-attachments/assets/1334b543-0faf-41a2-817a-59e35fa0695a)

**Comment by harshit078** [comment]
@Bonapara, you are correct ! It overflows through the navigation bar if the user scrolled down and it will not reposition itself.


https://github.com/user-attachments/assets/96073cc8-0e00-4e83-9eb2-b8eb37a6b6b3

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by harshrajeevsingh** [comment]
Hey, @Bonapara. I worked on this today and found that the datePicker component is overflowing not only on mobile but also on the desktop. The react-datePicker uses floating UI package to auto-position the element based on the viewport. 
After debugging, I found that floating UI is not working for the datePicker component because it's wrapped inside a parent div. Therefore, we need to remove the parent div to make this work. Down below I attached some screenshots to check. 
Lemme know what approach should I take.

Before: 
![Screenshot from 2024-10-04 01-28-18](https://github.com/user-attachments/assets/55d8c6f8-261d-4717-993a-2cdf2de2d9db)

After: 
![Screenshot from 2024-10-04 01-30-40](https://github.com/user-attachments/assets/10662039-3fcb-4b02-922a-4dd029ece027)
![Screenshot from 2024-10-04 01-31-47](https://github.com/user-attachments/assets/b969ae98-0619-44ac-b017-9d83d3142960)

**Comment by Bonapara** [comment]
@lucasbordeau will have a better idea on this ;)

**Comment by manav-gopal** [comment]
Hi @Bonapara , if this issue is still open, could you please assign it to me?

**Comment by harshrajeevsingh** [comment]
Hey @manav-gopal  Are you still working on this? I got it fixed. If you are not working unassign yourself. So, I can raise a PR.
