### ISSUE TITLE
Note & Task side panel should open faster

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7067]
# Current behavior

The side panel takes several seconds to open (8s for me). The user might press the button multiple times, creating several empty notes or tasks.

https://github.com/user-attachments/assets/6fa42d3f-6ef1-4de1-af14-761268385ac9

**Comment by FelixMalfait** [comment]
The issue is we need to (1) perform a creation request (2) use that response to open the panel with the right url.
So if for whatever reason (1) becomes slow (it shouldn't happen ideally), then it feels very slow. 
One solution would be to open the panel before with shimmers. It wouldn't improve the loading time but at least the panel would be open. I'm not sure if we should do it as the root cause is really that (1) is slow which really shouldn't have happened

**Comment by FelixMalfait** [comment]
@Bonapara I tested in prod this morning and loading time was surprisingly good. Seems like the migration of pg_graphql for create/update had a big impact! Please feel free to re-open a new issue if you think there's a path for even more improvements :)
