### ISSUE TITLE
Expose the FindManyRecord Filter as a DSL

### ISSUE THREAD

**Issue by Sytten** [twentyhq/twenty#7098]
## Scope & Context

I am working on a product in the security space that has a lot of similar characteristics to CRM, I have seen what is interesting to power users.

## Current behavior

Right now you expose a general search which uses predefined fields (name & emails) OR a filter per field by clicking on a field and clicking on filter. This is ok for basic use cases, but I am seeing the GraphQL go through and you can expose more to the power users.

## Expected behavior

What we did in [Caido is build a DSL](https://github.com/caido/httpql) that is parsed into the same filter that you have built.
So it could look like `(people.name.like:"%emile%" and people.company.eq:"Caido") or (people.name.cont:"other" and people.company.neq:"ACME")`

You then parse that with something like Lezer and you convert that to the same structure that you use right now in your GraphQL query.

There are many ways to build a DSL, [our spec](https://docs.caido.io/concepts/essentials/httpql.html) follows one popular way but it is more "technical" people friendly (it looks like code) than "regular" everyday people friendly (where it would look more like `deal > 100 and contact = "john"`

**Comment by FelixMalfait** [comment]
Hey @Sytten this is a great suggestion and I really hope we will get there.
There are already several issues covering this, such as #2443 or #6868 ; we're also going to merge #7700 which is another step towards more complex query (in the ui)
I'll close this because we'll tackle this sub-issue by sub-issue but thanks a lot for the feedback, we're aligned on the long-term direction we should take I think :)
