### ISSUE TITLE
Settings cards should use `<a> `instead of `<div>`

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7356]
# Current Behavior

The field type Settings cards use a `div` container.

![CleanShot 2024-09-30 at 17 07 51](https://github.com/user-attachments/assets/d37b5baa-e4e3-4074-98fb-13f54f8546f4)

This concerns the `field type` settings cards, but not the `emails` and `calendar` settings cards in Accounts (which use an `<a>` tag), even though they share the same component.

![c3713d6712bf11aee76f412aa0c7a7f4924c38eb2e06284424cb4ed830438ba7](https://github.com/user-attachments/assets/a2d3bf93-220a-4e20-b72a-095a555eb60c)

# Desired Behavior

They should use an `<a></a>` container for accessibility. Design and behavior should remain the same.

# Figma

![image](https://github.com/user-attachments/assets/777f9dd9-0903-4fb7-8437-ebbb4f0fb6ab)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=35741-193252&node-type=frame&t=YZppWDu8cDmzxDmJ-11

**Comment by sachinks07** [comment]
@Bonapara, I would like to work on this issue.

**Comment by ehconitin** [comment]
@sachinks07 Thanks for the interest!
Could you pick another [good first issue](https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)

**Comment by ehconitin** [comment]
@Bonapara 

![image](https://github.com/user-attachments/assets/f3aebef2-8147-4c3a-b96d-894c9f67960e)

These cards are wrapped inside <a> tags because they use an UndecoratedLink component with an href attribute. However, in the field type settings cards, there's no href or navigation link to trigger on click. Instead, they use onClick event handlers for interactivity.

**Comment by Bonapara** [comment]
Can we either use the <button> tag then or add role="button" in the HTML?

**Comment by FelixMalfait** [comment]
@ehconitin Actually I just found out we have already have the way to pass the field type through the url so we should be able to change the onClick to a proper link: https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/views/view-picker/hooks/useGetAvailableFieldsForKanban.ts#L38


As part of the issue, could you please also:
- delete all code related to `new-field/step-1` (route declaration, story, page), it isn't used anymore
-  `new-field/step-2` to just `/new-field` since there is just one step now

**Comment by ehconitin** [comment]
looking into it!

**Comment by Bonapara** [comment]
We could also try to fix this one in the same PR: https://github.com/twentyhq/twenty/issues/6967

**Comment by ehconitin** [comment]
@Bonapara yes, i will try!

**Comment by ehconitin** [comment]
> @ehconitin Actually I just found out we have already have the way to pass the field type through the url so we should be able to change the onClick to a proper link: https://github.com/twentyhq/twenty/blob/main/packages/twenty-front/src/modules/views/view-picker/hooks/useGetAvailableFieldsForKanban.ts#L38
> 
> As part of the issue, could you please also:
> 
> * delete all code related to `new-field/step-1` (route declaration, story, page), it isn't used anymore
> * `new-field/step-2` to just `/new-field` since there is just one step now

@FelixMalfait 
That hook wasnt working as it supposed to due to changes in `SettingsObjectNewFieldStep2`, fixed it!
But there are still two steps, let me explain - 
step 1 checks if there are any fields hidden, if not skips to step 2
inside step 2 there are 2 sub steps for filed selection and configuration, which has been recently changed to on step.
So, we should not remove step 1 related code right?

**Comment by FelixMalfait** [comment]
@ehconitin yes we should remove entirely the code related to step1, this step was confusing and we have dropped it, it’s not part of the flow anymore. Thanks!

**Comment by ehconitin** [comment]
> We could also try to fix this one in the same PR: #6967

@Bonapara this issue is redundant now right?

**Comment by Bonapara** [comment]
If we fix it in this PR, yes! Can you mention it in your PR so it closes both issues?

**Comment by ehconitin** [comment]
Yup!
