### ISSUE TITLE
Add Percentage Type in Number Field

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7375]
# Desired Behavior

We want to add a "percentage" type in the number field type.

![image](https://github.com/user-attachments/assets/20a6466f-37e1-4db4-9078-153d93112fb6)

We want to let the user choose the number of decimal the percentage should have.

**Comment by Bonapara** [comment]
/oss.gg 150

**Comment by FelixMalfait** [comment]
Blocked by #7340 wait for this PR to be merged first

**Comment by motuz0001** [comment]
hey, is it still possible to work on this one?

**Comment by Bonapara** [comment]
Hi @motuz0001, we need to wait for #7340 but after yes ;)

**Comment by Owaiseimdad** [comment]
Team @Bonapara , facing issue during local setup
<img width="1128" alt="Screenshot 2024-10-17 at 12 34 11 AM" src="https://github.com/user-attachments/assets/907f414b-35b0-44e9-9e16-29bec1ed9891">

**Comment by Owaiseimdad** [comment]
➤ YN0060: │ @nestjs/common is listed by your project with version 9.4.3 (p65958), which doesn't satisfy what @golevelup/nestjs-discovery (via nest-commander) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ @nestjs/core is listed by your project with version 9.4.3 (p66425), which doesn't satisfy what @golevelup/nestjs-discovery (via nest-commander) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ @ptc-org/nestjs-query-core is listed by your project with version 4.4.0 (p1c853), which doesn't satisfy what @ptc-org/nestjs-query-typeorm requests (4.2.0).
➤ YN0060: │ @swc/core is listed by your project with version 1.3.107 (p2dbb7), which doesn't satisfy what @swc-node/core (via @swc-node/register) and other dependencies request (^1.4.13).
➤ YN0060: │ esbuild is listed by your project with version 0.23.0 (pdd602), which doesn't satisfy what esbuild-plugin-svgr and other dependencies request (~0.19.1).
➤ YN0060: │ graphql is listed by your project with version 16.8.0 (peb3fc), which doesn't satisfy what graphiql-explorer (via @graphiql/plugin-explorer) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ passport is listed by your project with version 0.7.0 (pc5831), which doesn't satisfy what @nestjs/passport requests (~0.4.0 || ~0.5.0 || ~0.6.0).
➤ YN0060: │ react is listed by your project with version 18.3.1 (p5b305), which doesn't satisfy what @react-email/components and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ react-dom is listed by your project with version 18.3.1 (p7e651), which doesn't satisfy what graphiql-explorer (via @graphiql/plugin-explorer) and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ vite is listed by your project with version 5.4.0 (p5f036), which doesn't satisfy what @crxjs/vite-plugin and other dependencies request (but they have non-overlapping ranges!).
➤ YN0002: │ twenty-front@workspace:packages/twenty-front doesn't provide react (pd36df), requested by @nivo/calendar and other dependencies.
➤ YN0002: │ twenty-front@workspace:packages/twenty-front doesn't provide react-dom (p66e11), requested by @xyflow/react.
➤ YN0002: │ twenty-server@workspace:packages/twenty-server doesn't provide @apollo/gateway (pc2c97), requested by @ptc-org/nestjs-query-graphql.
➤ YN0002: │ twenty-server@workspace:packages/twenty-server doesn't provide @nestjs/common (p60764), requested by @graphql-yoga/nestjs and other dependencies.
➤ YN0002: │ twenty-server@workspace:packages/twenty-server doesn't provide @nestjs/core (p7a89f), requested by @graphql-yoga/nestjs and other dependencies.
➤ YN0002: │ twenty-server@workspace:packages/twenty-server doesn't provide class-transformer (p44b0e), requested by @nestjs/graphql and other dependencies.
➤ YN0002: │ twenty-server@workspace:packages/twenty-server doesn't provide esbuild (p79636), requested by @esbuild-plugins/node-modules-polyfill.
➤ YN0002: │ twenty-server@workspace:packages/twenty-server doesn't provide graphql (pc4e0d), requested by @graphql-yoga/nestjs and other dependencies.
➤ YN0002: │ twenty-server@workspace:packages/twenty-server doesn't provide graphql-subscriptions (p870ad), requested by @ptc-org/nestjs-query-graphql.
➤ YN0002: │ twenty-server@workspace:packages/twenty-server doesn't provide graphql-yoga (pf7fe3), requested by @graphql-yoga/nestjs.
➤ YN0002: │ twenty-server@workspace:packages/twenty-server doesn't provide react (p83320), requested by @monaco-editor/react and other dependencies.
➤ YN0002: │ twenty-server@workspace:packages/twenty-server doesn't provide react-dom (p37882), requested by @monaco-editor/react and other dependencies.
➤ YN0002: │ twenty-server@workspace:packages/twenty-server doesn't provide reflect-metadata (p8a9bd), requested by @nestjs/graphql.
➤ YN0002: │ twenty-server@workspace:packages/twenty-server doesn't provide rxjs (pdddd9), requested by @nestjs/cache-manager.
➤ YN0002: │ twenty-server@workspace:packages/twenty-server doesn't provide ts-morph (pc2108), requested by @nestjs/graphql and other dependencies.
➤ YN0002: │ twenty-server@workspace:packages/twenty-server doesn't provide zod (pc7124), requested by zod-to-json-schema.
➤ YN0002: │ twenty-website@workspace:packages/twenty-website doesn't provide react (pe750b), requested by @docsearch/react and other dependencies.
➤ YN0002: │ twenty@workspace:. doesn't provide @envelop/core (p26b5b), requested by @envelop/on-resolve.
➤ YN0002: │ twenty@workspace:. doesn't provide @graphiql/react (pe7fb2), requested by @graphiql/plugin-explorer.
➤ YN0002: │ twenty@workspace:. doesn't provide @nestjs/graphql (p41b76), requested by @nestjs/apollo.
➤ YN0002: │ twenty@workspace:. doesn't provide @storybook/components (p63b67), requested by storybook-addon-cookie and other dependencies.
➤ YN0002: │ twenty@workspace:. doesn't provide @storybook/core-events (pd0be4), requested by storybook-addon-pseudo-states.
➤ YN0002: │ twenty@workspace:. doesn't provide @storybook/manager-api (pa7eb0), requested by storybook-addon-cookie and other dependencies.
➤ YN0002: │ twenty@workspace:. doesn't provide @storybook/preview-api (p8feff), requested by storybook-addon-cookie and other dependencies.
➤ YN0002: │ twenty@workspace:. doesn't provide @storybook/theming (p16650), requested by storybook-addon-pseudo-states.
➤ YN0002: │ twenty@workspace:. doesn't provide @storybook/types (p68c69), requested by storybook-addon-cookie.
➤ YN0002: │ twenty@workspace:. doesn't provide @types/inquirer (pf55ec), requested by nest-commander.
➤ YN0002: │ twenty@workspace:. doesn't provide express (pe4ca2), requested by @nestjs/serve-static and other dependencies.
➤ YN0002: │ twenty@workspace:. doesn't provide prop-types (p635d5), requested by iframe-resizer-react.
➤ YN0002: │ twenty@workspace:. doesn't provide reflect-metadata (p10b76), requested by @nestjs/common and other dependencies.
➤ YN0002: │ twenty@workspace:. doesn't provide scheduler (pa4e11), requested by use-context-selector.
➤ YN0002: │ twenty@workspace:. doesn't provide typeorm (pd60ef), requested by @nestjs/terminus and other dependencies.
➤ YN0002: │ twenty@workspace:. doesn't provide webpack (p16bcb), requested by css-loader and other dependencies.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 8s 76ms
➤ YN0000: ┌ Link step
➤ YN0008: │ @sentry/profiling-node@npm:8.30.0 must be rebuilt because its dependency tree changed
➤ YN0008: │ esbuild@npm:0.18.20 must be rebuilt because its dependency tree changed
➤ YN0008: │ @swc/core@npm:1.7.6 [40dfc] must be rebuilt because its dependency tree changed
➤ YN0008: │ bcrypt@npm:5.1.1 must be rebuilt because its dependency tree changed
➤ YN0008: │ better-sqlite3@npm:9.6.0 must be rebuilt because its dependency tree changed
➤ YN0008: │ core-js@npm:3.38.0 must be rebuilt because its dependency tree changed
➤ YN0008: │ esbuild@npm:0.19.12 must be rebuilt because its dependency tree changed
➤ YN0008: │ esbuild@npm:0.23.0 must be rebuilt because its dependency tree changed
➤ YN0008: │ sharp@npm:0.32.6 must be rebuilt because its dependency tree changed
➤ YN0008: │ @nestjs/core@npm:9.4.3 [0915e] must be rebuilt because its dependency tree changed
➤ YN0008: │ @swc/core@npm:1.3.107 [0915e] must be rebuilt because its dependency tree changed
➤ YN0008: │ msw@npm:2.3.5 [0915e] must be rebuilt because its dependency tree changed
➤ YN0008: │ esbuild@npm:0.21.5 must be rebuilt because its dependency tree changed
➤ YN0008: │ iframe-resizer@npm:4.4.5 must be rebuilt because its dependency tree changed
➤ YN0008: │ msgpackr-extract@npm:3.0.3 must be rebuilt because its dependency tree changed
➤ YN0008: │ core-js@npm:2.6.12 must be rebuilt because its dependency tree changed
➤ YN0008: │ @apollo/protobufjs@npm:1.2.7 must be rebuilt because its dependency tree changed
➤ YN0008: │ nice-napi@npm:1.0.2 must be rebuilt because its dependency tree changed
➤ YN0008: │ @apollo/protobufjs@npm:1.2.6 must be rebuilt because its dependency tree changed
➤ YN0008: │ es5-ext@npm:0.10.64 must be rebuilt because its dependency tree changed
➤ YN0008: │ core-js-pure@npm:3.38.0 must be rebuilt because its dependency tree changed
➤ YN0008: │ nx@npm:18.3.3 [0915e] must be rebuilt because its dependency tree changed

**Comment by Bonapara** [comment]
@Owaiseimdad please ask on our https://discord.com/invite/cx5n4Jzs57 #help channel :)

**Comment by Khaan25** [comment]
@Bonapara Could you assign me please

**Comment by Bonapara** [comment]
First, address your ongoing issues, @Khaan25 🙏
