### ISSUE TITLE
Improve scrolling in the table

### ISSUE THREAD

**Issue by harshit078** [twentyhq/twenty#7515]
## Bug Description

- In Tables, when scrolled the animation is not smooth and always snaps to cursor to follow it instead of making a smooth transition
- This is very noticeable in mobile and can be frustating at times as if the user wants to read the value of first column then it is quite difficult to adjust the scoll accordingly

## Current Behaviour

https://github.com/user-attachments/assets/f4775401-55b7-4c9f-9e57-3d7351c0f2de

https://github.com/user-attachments/assets/b9ae180e-f590-4d64-a996-0bb61954b0e6

## Expected behavior

A smooth transition should be occupied when scrolled

**Comment by Bonapara** [comment]
/oss.gg 300

**Comment by Adithyan777** [comment]
Hi,
I noticed a couple of things with the current table behavior and wanted to confirm if I understand the issue correctly:

1. Smooth Scrolling: The scrolling animation feels a bit abrupt, particularly in mobile view. It seems like the first column (or part of it) is "stuck" during the scroll, causing it to snap to the cursor rather than transitioning smoothly. [This might need fixing.]

2. Inconsistent Fixed Column Behavior: For screens smaller than `md`, only the logo in the first column is fixed, while the rest of the first column scrolls away with the table.
**Was this a design choice, or should the entire first column (as it is on larger screens) be fixed as well??**

**Comment by Bonapara** [comment]
Thanks for your comment. 
2. is indeed a choice @Adithyan777!

**Comment by Khaan25** [comment]
Here's a preview of the improved smooth scrolling in the table.

https://github.com/user-attachments/assets/c413afc7-db51-47fd-ba4c-a7c095de5a95

**Comment by Khaan25** [comment]
@Bonapara @harshit078

**Comment by Bonapara** [comment]
Thanks @Khaan25! I think the left column should not move, can you fix that?

**Comment by Khaan25** [comment]
Actually, on mobile devices, it's moving because we don't have first column to have full width.

On desktop it's not moving.

**Comment by Bonapara** [comment]
To clarify, I think it's fine that the cell width is reduced. What looks strange is the spacing around the checkbox, which seems to move as well. 


https://github.com/user-attachments/assets/7b73568f-2ebf-4308-a6ce-7db136a67f3d

Only the column width should move, not the spacing inside the cell

**Comment by Khaan25** [comment]
Yeah. I'm fixing that - I think it's due to position: sticky but I'll have a look

**Comment by Khaan25** [comment]
Here you go: @Bonapara 


https://github.com/user-attachments/assets/50ad1765-bb00-4d1a-87ce-8eb8eb57f460

**Comment by lucasbordeau** [comment]
@Bonapara Is it fixed for you ?
