### ISSUE TITLE
Field on label should change singular to plural based on relation type

### ISSUE THREAD

**Issue by ehconitin** [twentyhq/twenty#7683]
## Current behavior
1) The field on label is populated with active object, and it doesn't change singular to plural or vice versa based on relation type.

![1](https://github.com/user-attachments/assets/b05ba455-28f5-4e8c-a694-682045759bca)

## Expected behavior
1) The label field on should automatically change from singular to plural (or vice versa) based on the relation type, unless the user manually edits or changes the field.

**Comment by ehconitin** [comment]
/oss.gg 200

**Comment by Cyanhead** [comment]
Hi @ehconitin, I'm having some difficulty with where exactly to implement the fix for this issue. I have an idea of the cause, but i'm not sure where/how to pass the data.

PHOTO A: It looks like the reason the plural is not being applied is because the `initialRelationFieldMetadataItem.label` gotten from the `useRelationSettingsFormInitialValues` hook doesn't get assigned the correct value.

PHOTO B: `initialRelationType` receives `relationTypeFromFieldMetadata` as undefined and defaults to `RelationDefinitionType.OneToMany`.

PHOTO C: The `SettingsDataModelFieldSettingsFormCard` component passes three properties, of which `relationDefinition` needed by the `useRelationSettingsFormInitialValues` isn't included.

<img width="644" alt="Screenshot 2024-10-16 102328" src="https://github.com/user-attachments/assets/2b1e98c2-4bb8-4416-8bbd-d120a5104df1">
<img width="671" alt="Screenshot 2024-10-16 102834" src="https://github.com/user-attachments/assets/e88c363a-e172-4344-a3fb-3c1f88b7ff02">
<img width="683" alt="Screenshot 2024-10-16 103139" src="https://github.com/user-attachments/assets/ee85e0f7-2649-40da-bb12-7265ffa9be6a">

**Comment by omarNaifer12** [comment]
@FelixMalfait  @ehconitin  Hello,
Sorry for working on this before being assigned. I've completed the task and made a pull request. Please review and let me know if any changes are needed.

Thank you!

**Comment by ehconitin** [comment]
@omarNaifer12 no problem! Thanks 😊
