### ISSUE TITLE
Improve table unnamed record cells behavior

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#7851]
# Current Behavior

Behavior of records without a name:

-  Default state: An empty cell is displayed.
-  Hover state: A chip with the record icon identifier appears. Clicking on it allows the user to navigate to the record detail page. Clicking the empty cell allows renaming the record. No `arrow up right` floating icon button is displayed.

https://github.com/user-attachments/assets/016b2b83-cecd-4737-a702-15c843793aa1

# Desired Behavior

### Default State
-  Remain as is (Empty).

### Hover State
-  Do not display the relation chip.
-  Show `Set Name` as a placeholder. On click, open the name input.
-  Display the `arrow up right` floating icon button, similar to records with a name, to navigate to the record detail page.

https://github.com/user-attachments/assets/f60725c4-4b9a-4052-8bae-32e66ec67c82

# Figma

Make sure to update the component

![image](https://github.com/user-attachments/assets/88135795-c3a8-4859-9305-f4742e898936)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=14603-76540&node-type=frame&t=iBqOKbAA8s4yWFu2-11

**Comment by Bonapara** [comment]
/oss.gg 300

**Comment by adityadeshlahre** [comment]
Hey @Bonapara and @naaa760 @sanjay-gangwar4410 @pramittt this issue is open to take!
it seems like this issue needs more context-gathering { I tried with my local setup done } I wasn't able to replicate the desired behavior in the `Companies Tab`. Hence it was hard to get this done for me so I am unassigning this issue.

## POV 
![replication](https://github.com/user-attachments/assets/e88619a3-6214-451a-86b5-2df49fb42886)

you guys can get this issue assigned :slightly_smiling_face: 
I think I need to give more time to twenty repo :clock1: 

Thank You

**Comment by harshrajeevsingh** [comment]
@Bonapara I would like to work on this issue :)
