### ISSUE TITLE
Update Cell/Field relation style

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#799]
Any "People" and "Companies" relations, either in fields or cells, should be contained in chips with a visible background. When I click on one of these chips, I should go to the corresponding "People" or "Company" page. These fields/cells should use the "show edit button" to edit the relation when needed.

# Actual behavior

### Cells

Companies' relations on the "People" table
![Image](https://github.com/twentyhq/twenty/assets/19412894/2a3c8087-57e1-41a0-aaf2-7ff917c46ded)

### Fields

Opportunities main contact
![Image](https://github.com/twentyhq/twenty/assets/19412894/d315b8ac-2818-42ad-9ea0-3a275ded3f25)

People show company relation:
![Image](https://github.com/twentyhq/twenty/assets/19412894/2ffc4487-c8d5-4d70-ad36-28b4eae65c2c)

# Desired behavior

### Cells
https://github.com/twentyhq/twenty/assets/19412894/1b23c73c-1a6f-42ee-8f71-2867c9a503f8

On cells, the "show edit button" should be placed in absolute position on the right side of the cell.

### Fields
https://github.com/twentyhq/twenty/assets/19412894/3633bd81-4dc1-488b-ae06-d472dae115cf

On Fields, the "show edit button" should come directly after the chip (already implemented)

# Figmas

People: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=568-41746&mode=design&t=GMBHxG3P5dZsG4iz-4

Opportunities: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5910-77816&mode=design&t=GMBHxG3P5dZsG4iz-4

Press play to see the prototype behavior!

**Comment by FelixMalfait** [comment]
When you say "The design is the same as Shows and Note/tasks popups" do you mean that as part of this ticket we should also update the property box in show page? And the assignee field in tasks? Or other fields? Because I don't see that new chip currently implemented on the show page

<img width="185" alt="Screenshot 2023-07-22 at 22 06 54" src="https://github.com/twentyhq/twenty/assets/6399865/8d1decc4-c2db-4ebd-80b2-afa3c8670b38">

**Comment by Bonapara** [comment]
Description has been updated after discussing with @charlesBochet
