### ISSUE TITLE
I should be able to filter on workspaceMember = me

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#8016]
## Context
In https://github.com/twentyhq/twenty/pull/7196 we introduce "variable filters" such as "today" or "in the future", in which the frontend dynamically replaces the value before throwing the query.

## Current behavior

<img width="535" alt="Screenshot 2024-10-23 at 22 41 07" src="https://github.com/user-attachments/assets/b0b29251-7d2d-4277-93cb-d409a82e589b">

## Desired behavior
We would like to introduce a "current user" option for workspaceMember relations, for example assignee on Tasks.

See how Linear is also doing it:

<img width="242" alt="Screenshot 2024-10-23 at 22 43 43" src="https://github.com/user-attachments/assets/990e12d9-5ad1-47ff-8fb3-8026633b4d4e">

# Figma

- Change no owner icon to `circle-dashed-x`
- The text for "is empty" should be `no field-name` e.g no owner, no assignee...
- Create a new `me` value with `user-circle` icon

![CleanShot 2024-10-24 at 13 46 55](https://github.com/user-attachments/assets/89cd11f3-0e0f-45c8-a527-e0a9c8bb6e46)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=43752-81861&node-type=instance&t=tFDldeynurqAJQpp-11

**Comment by ketanMehtaa** [comment]
assign me if sanjay is not working on this .

**Comment by sanjay-gangwar4410** [comment]
i am not working on it . you (@ketanMehtaa )can work on it

**Comment by FelixMalfait** [comment]
/oss.gg 1000

**Comment by NabidAkhtar** [comment]
@sanjay-gangwar4410 please unassign yourself, if you are not working.

**Comment by eliasylonen** [comment]
### Some rubber ducking / notes:

I need to add something like `CURRENT_WORKSPACE_MEMBER` as a possible filter value for `RELATION` filters, and convert it into a workspace member id in `resolveFilterValue`.

To do this, `resolveFilterValue` needs to know the id of current workspace member.

I think passing `currentWorkspaceMemberId` to `resolveFilterValue` as a parameter is not a very elegant long-term solution, because resolveFilterValue might need many more similar parameters in the future when more "variable" filters (like `PAST_3_WEEKS` for `DATE` filters and `CURRENT_WORKSPACE_MEMBER` for `RELATION` filters) are added.

I think it would be good to wrap `resolveFilterValue` with a hook (e.g. `useResolveFilterValue`) to avoid having to supply all its dependencies as parameters.

---

**TODO - continuing here tomorrow:** Is there any reason against wrapping all functions where resolveFilterValue is used with hooks to be able to use the `useResolveFilterValue` hook inside them? Probably no.

---

In the long term I think the most elegant solution would be to call the `useResolverFilterValue` hook as early as possible: The current `Filter` type could be changed to contain the resolved filter value instead of the unresolved value from the original `ViewFilter`. That way filtering-related components would not have to do any value resolving at all, they could just always use the resolved value.

Downside: That would be a bigger refactoring than I first thought.

**Comment by FelixMalfait** [comment]
Thanks @eliasylonen!

**Comment by eliasylonen** [comment]
@lucasbordeau 
Some context for today's call, but no need to prep! I have a list of questions ready

Filter value resolution in object filter component:
https://github.com/eliasylonen/twenty/commit/354c94a1824fe5aecdde4e5a66cc804ca3fbf6bb

Passing current workspace member id to the util function that generates the GraphQL query - I think a hook would be better?
https://github.com/eliasylonen/twenty/commit/d86416a54ad8af91157f33585ffc8281b480e85d
