### ISSUE TITLE
Notes & tasks taken on People should also appear in their company show

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#805]
If I take note of a company team member, then the company should automatically be preselected when I add a note

<img width="888" alt="Screenshot 2023-08-02 at 18 45 23" src="https://github.com/twentyhq/twenty/assets/6399865/4af102bd-7412-4986-ab51-aa1710a50559">

(Note: there are lots of hidden comments because we initially proposed a more complex solution, then edited the issue for a much simpler solution)

**Comment by FelixMalfait** [comment]
@Bonapara  Should we display a different text above the note in the timeline when it comes from a person?

**Comment by FelixMalfait** [comment]
Currently we have an endpoint where we can fetch activities for several commentThread at once.
 So one option would be to 1) fetch and display the people that belongs to a company (we probably want that @Bonapara no?) 2 pass the ids we just fetched to the current request
 Another option would be to modify the current request so that when an id of a company is passed, the people's notes are fetched automatically.
 A third option similar to the second, would be to create a new dedicated endpoint that does it and keep the current one as is.
 
 cc @charlesBochet for recommandation

**Comment by charlesBochet** [comment]
Technically, the solution 2) is easier than 3) as we don't have a fine control on the API right now (it's autogenerated by prisma-nestjs-graphql package)

**Comment by Bonapara** [comment]
Possible design:

![Image](https://github.com/twentyhq/twenty/assets/19412894/dcf37242-90e7-4b29-9d3a-c874629909d9)

**Comment by FelixMalfait** [comment]
@Bonapara don't you feel that it would make it pointless then to be able to assign a note to a company and a person at the same? since we have a multi-relation picker that makes it easy I now wonder if this should be prioritized

**Comment by Bonapara** [comment]
I agree. I think what we should do is to auto add the company relation when creating a People note or task (And allow the user to remove it afterwise). For instance, if I create a Note for Brian Chesky, I should add relations to both "Brian Chesky" and "Airbnb".

**Comment by FelixMalfait** [comment]
I agree!
