### ISSUE TITLE
Add ability to select a default country for the Address and Phone fields

### ISSUE THREAD

**Issue by 123remodeling** [twentyhq/twenty#8081]
## Scope & Context

All our opportunities, employees and other contacts are in the US and I would like to make Address field to use the United States as a default country. It's tiresome to change it manually all the time.

## Current behavior

Currently, the Country in the Address field defaults to `null` (but shows _Ascention Island_ for some reason, which is confusing).

## Expected behavior

Ability to select the default country on the field level for Address field. I think it would be also useful to add an ability to use a default State for companies that operate only in a single State.

**Comment by FelixMalfait** [comment]
Good point. We already have a similar capabilty for currency (default unit) so whoever implements this can take inspiration from it.

We should also consider adding it for phones (but for phone we should be able to leave it as blank / with no default country, like today)

**Comment by Bonapara** [comment]
![Uploading image.png…]()

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=34845-128087&node-type=frame&t=WdI3ZY5Lsc7ylyqB-11

**Comment by 123remodeling** [comment]
@Bonapara looks good!

**Comment by Bonapara** [comment]
Sure @sreyas-b-anand, thanks for contributing!

**Comment by Bonapara** [comment]
Sure @sri-c9 , thanks for contributing!

**Comment by sri-c9** [comment]
sorry i thought this was nextjs not nestjs

**Comment by Bonapara** [comment]
@guillim great point, we can add a "No country" value in the dropdown

![Image](https://github.com/user-attachments/assets/b3e9525e-246b-4dba-9476-1342a68314df)

https://www.figma.com/design/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=24182-600671&node-type=instance&t=DtzuFw1XVhAUBGqX-11

**Comment by FelixMalfait** [comment]
@guillim I checked after our conversation and the default currency is actually set on the frontend when editing a currency field. Which means it's set to null by default but if you open/close the input then it'll be set to your default value. We don't really feel it on the currency field because there's also an additional condition so that we shouldn't display anything unless the amount is not null.
I think that behavior is fine and we could have the same behavior on phone numbers (also hiding the number if only the country has been recorded).

For the address field type it's slightly more annoying because if we open/close the address field and it has a default value, then the country will become visible in read-only mode because we don't require setting an address to display it.
I don't think it's a big issue because:
- the user can always set the value back to null manually since you'll introduce that option
- in the future, we will likely introduce additional settings on the address field later to allow the user adjust the address display format.
- in the future, there will be other evolutions to the address field which could impact the decision (e.g. add Google Maps auto-complete)

Overall I don't think it's worth overthinking this feature. We should go with whatever makes more sense for you.

**Comment by JorgeGraciaViveros** [comment]
Hi @Bonapara! I am currently working in a group of 5 students from CMU taking an introductory software engineering course and our final project is to contribute to an open-source repo. Our project has multiple checkpoints and will be due on December 8 (meaning our PR will take longer to open). Would it be possible for us to be assigned to this issue (or any issues that you think would be a good fit)? Thanks!

**Comment by Bonapara** [comment]
Sorry @JorgeGraciaViveros, @guillim is already on it
