### ISSUE TITLE
Add Companies or People to favorite

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#820]
When I click on the heart, it adds the card to a favorite section.

![Image](https://github.com/twentyhq/twenty/assets/19412894/91f70a8a-b2c7-4611-a239-94b283bec427)

![Image](https://github.com/twentyhq/twenty/assets/19412894/f58b6db1-721c-48b9-ad46-1805d0e51a8c)

![Image](https://github.com/twentyhq/twenty/assets/19412894/8cc2e2bb-4020-48e0-80f3-db433e28ba42)

**Comment by FelixMalfait** [comment]
I guess it's at the user-level not workspace level, right?

Two precisions for backend implementation (cc @charlesBochet if you disagree):
- reference workspace_member_id instead of user_id
- use 1 column per favoritable_type instead of using two columns _type/_id to represent all possible types

So on the backend side, table could probably look like this:
```
CREATE TABLE favorites (
    id INT PRIMARY KEY,
    workspace_member_id INT,
    company_id INT,
    person_id INT,
    FOREIGN KEY(user_id) REFERENCES users(id),
    FOREIGN KEY(company_id) REFERENCES companies(id),
    FOREIGN KEY(person_id) REFERENCES people(id),
);
```

**Comment by Ashwini-Tekion** [comment]
Hi @Bonapara @FelixMalfait , this project looks amazing and I want to contribute to the issue. 

Is there a front end contribution required to this issue?

**Comment by FelixMalfait** [comment]
Thanks a lot @Ashwini-Tekion! 

Steps on the frontend would be:
- implementing the button on top right
- implement list of favorites on the left menu
- add storybook test

The thing is  that half of the frontend work is around hooking the parts to the backend.
And in order to do this, the steps are usually:
1 - create graphql endpoint on the backend
2 - run `yarn graphql:generate` on the frontend which pulls the backend schema and create the hooks on frontend
3 - create queries on the frontend (e.g. look at files called "show.tsx")
4 - call those queries from the frontend

So it would be easier for you if the backend endpoint already existed, than doing the frontend at first.

Figma for reference:
"heart button" component there: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=2971%3A172331&mode=dev and red color reference https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=3171%3A43801&mode=dev there. Note that we have a theme file so colors should always come from there.
You can also see all the other screens on the Figma

There are pure-frontend issues that are probably easier to start with before you get familiar with the codebase:
- https://github.com/twentyhq/twenty/issues/807
- https://github.com/twentyhq/twenty/issues/788
- https://github.com/twentyhq/twenty/issues/753
- https://github.com/twentyhq/twenty/issues/710
- https://github.com/twentyhq/twenty/issues/700

Let me know on the issue if you'd like to be assigned to any of them

**Comment by Bonapara** [comment]
Favorites should indeed be attached to the user level

**Comment by AdityaPimpalkar** [comment]
Hi @Bonapara, Can I take this up?

**Comment by FelixMalfait** [comment]
@AdityaPimpalkar sure thanks a lot!
Have you ever worked with NestJS? This ticket is a good first issue in the sense that the instructions are clear but it's still a full-stack task so not the easiest one

**Comment by AdityaPimpalkar** [comment]
Thanks @FelixMalfait! 
Not much experience with NestJS, but I am willing to learn. I have already made some progress too! If I do get stuck on something I'll post my query here or on community discord. Thanks! :)
