### ISSUE TITLE
On the kanban view, when I export my data for the first time, download is triggered twice

### ISSUE THREAD

**Issue by thomtrp** [twentyhq/twenty#8239]
## Bug Description

On Kanban view, when I try to export data for the first time, these are downloaded twice.

This only happens the first time. Once the authorization is given, the file is only downloaded once.

https://github.com/user-attachments/assets/b52c3a1a-a5c0-4366-90cb-404c8291163c

## Expected behavior

Only one download should be triggered.

**Comment by Bonapara** [comment]
Related:

https://github.com/twentyhq/twenty/issues/6729
https://github.com/twentyhq/twenty/issues/8098

**Comment by parmarKaran01** [comment]
@thomtrp @Bonapara this issue is consistently reproducible and not only in Kanban view but table view as well
### Steps to reproduce

1. Clear the application data
2. Login
3. go to any table and try to export ( for the first time it will get downloaded twice, but the second time when you click on download its working as expected )

**Comment by parmarKaran01** [comment]
Also need some big files to test out the fix properly, if you guys have any dummy big file that is available and you can share that would help!
