### ISSUE TITLE
Support for "Between" Filter for Date Fields

### ISSUE THREAD

**Issue by asdev29** [twentyhq/twenty#8355]
### **Description:** 
Currently, the date fields in the application do not support a "between" filter. The limitation allows setting only one filter per field (either `gt` or `lt`), which restricts users from filtering date fields within a specific range. This enhancement would add flexibility to queries, improving user experience and reducing workarounds.

### **Requested Feature:**

- Add "Between" Filter: Enable a "between" filter option for date fields, allowing users to specify both gt (greater than) and lt (less than) constraints simultaneously for the same field.
- Alternative Solution: Allow the application to set two filters (gt and lt) for the same date field if a "between" filter is not feasible.

### **Example Use Case:** 
A user wants to retrieve records where a date field falls between two specific dates (e.g., `startDate` and `endDate`). Currently, they can only filter for dates greater than a specific date or less than a specific date, but not both. The "between" filter would streamline such range-based queries.

**Comment by FelixMalfait** [comment]
Hey, this is coming very soon, we have shipped "advanced filters" but it's behing a feature flag. That will allow you to do complex query like [(if A or B) AND (C or (D and E)). I think we will remove the feature flag in ~2 weeks :). Closing since I consider most of the work is done but feel free to reply!
