### ISSUE TITLE
Error field type rich text

### ISSUE THREAD

**Issue by chsasank** [twentyhq/twenty#8445]
![image](https://github.com/user-attachments/assets/21d95769-29cc-4fdb-9a86-28dd12037d82)

Getting this once in a while when I edit notes. On refresh I don't see what I typed in title

![image](https://github.com/user-attachments/assets/8af96ef3-9313-4026-a218-5217331614c6)

**Comment by Bonapara** [comment]
@chsasank, thank you for raising this issue. Is there any specific context that might help us reproduce it?

**Comment by chsasank** [comment]
It happens when I create a new note from profile screen. Happens fairly often. Using self hosted 0.31.0

**Comment by FelixMalfait** [comment]
https://github.com/twentyhq/twenty/blob/lain/packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.ts#L318

I'm guessing that to reproduce you need to set a filter on the task/notes view on the body field. And then this causes an optimistic rendering issue when trying to update the queries following the note update

**Comment by chsasank** [comment]
I don't need to put in a filter to get this. Just create a new note from profile screen and start editing title. You'll get it once in a while.

**Comment by chsasank** [comment]
Relevant code is here: https://github.com/twentyhq/twenty/blob/cfe3515aa616a7f8fbfd4658daa1bb3d827701bd/packages/twenty-front/src/modules/object-record/record-filter/utils/isRecordMatchingFilter.ts#L318

This error is quite frustrating. Tell me how to fix it. I'll make a PR!

**Comment by FelixMalfait** [comment]
OK I managed to reproduce it, it seems to be linked to the command bar results (that's where we look for tasks and filter them by the body content, see CommandMenu.tsx). 

I think there's fundamental underlying work to do on the rich_text field (discussed here https://github.com/twentyhq/twenty/issues/7613#issuecomment-2408944585)
In the meantime we can just push a very basic implementation so that the error is ignored
