### ISSUE TITLE
Zapier Cannot Be Activated or Published 

### ISSUE THREAD

**Issue by jackbeeby** [twentyhq/twenty#8537]
After updating to 0.33 it prompted me to update the twenty app on zapier. I had done this which then included all new record labels. After setting up and going to activate it came couldn't activate and sent an email regarding the array below. 

Self hosted instance, zapier is able to connect, and test retrieval of all the records correctly however when publishing or clicking the on button it comes up with this fatal error. This is an error on the twenty side.![Image](https://github.com/user-attachments/assets/c2b92636-a6a2-4e75-b680-ac5213569db1)

**Comment by BOHEUS** [comment]
@martmull

**Comment by martmull** [comment]
Thanks @BOHEUS for pinging me. Hey @jackbeeby, we recently updated the webhook table so that `operation` string column is replaced by an `operations` array column

When I read the error message you provided, I see that your self hosted backend is looking for an `operation` parameter, and not an `operations` parameter.  

From which version did you upgrade to 0.33?
Did you follow the upgrade guide? -> https://twenty.com/developers/section/self-hosting/upgrade-guide
We recommend to upgrade version by version

If you properly followed the upgrade guide, I would suggest to manually sync-metadata: with the command `yarn command:prod workspace:sync-metadata -f` (dump your data before please)

Hope it helps
