### ISSUE TITLE
💡 Change strategy to implement morph relationships

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#855]
In comment_threads (activities) and in pipeline_progresses, we have implemented morph with two columns `xxable_type` and `xxxable_id`. This introduces limitations, such as the inability to define foreign keys in the database.

Instead we would like to move to a new table structure where we create a new column for each object we want to support.

This is a migration that need to be handle in multiple steps:
- change the way we morph on pipeline_progress by introducing a person_id and company_id
- make the front-end/backend support both
- make a manual data migration
- create a ticket to deprecate the old fields after that

```[tasklist]
### Tasks
- [ ] https://github.com/twentyhq/twenty/issues/856
- [ ] https://github.com/twentyhq/twenty/issues/857
```

**Comment by emilienchvt** [comment]
### Context
`Activity` and `PipelineProgress` both have the ability to link objects that can be hetorogeneous (`Company` or `People`, maybe more in the future).
Today we do this by having `xxxable_id` and one xxxable_type` fields on these types to be able to create relations to objects from any type, called `morphs`.
This poses a limitation because we can't write gql queries that access children of the morph.

The solution proposed above is to have one foreign key field per possible type linked (so in our example: `companyId` AND `peopleId`) and have only one populated.
Is that understanding correct ?

### Limitations
It might come with the following problems:
- Painful to implement and maintain the consistency of the morph property: _One and only one of the foreign keys is set_
- When adding a new type that should be useable as a morph (For example `Meeting` might have `activities` in the future), we'll have to update the morph type to add a column.
- We'll have to build frontend gql queries that go down the path of each of the possible children types to fetch the necessary properties
- Still on the frontend, we'll have to build custom logic for each of these diverse entities: should we show a company chip or a person chip as the target of the activity ?

The above limitations might be more and more painful as we see the list of possible types grow.

### Proposal
I liked the approach proposed in [this thread](https://stackoverflow.com/questions/34232966/graphql-schema-to-handle-mixed-types?rq=3): we build an interface that is implemented by the children types.
Such an interface for `ActivityTarget` might look like:

```
#Interface for any search result
interface ActivityTarget {
  id: String!
  displayName: String!
  pictureUrl: String!
}
```

We could then have a single `activity.targets: ActivityTarget` field that would contain indifferently `Companies` and `People` and we could use both the same way in the frontend.

**Comment by charlesBochet** [comment]
Yes, your understanding is correct!
I think we should distinguish the database issue from the frontend issue. 

**On the database side**, having `personId` + `companyId` will help maintaining a data integrity with foreign keys. For example right now, you can delete a company in database and still having an `ActivityTarget` pointing on it. 
Here is an interesting article about the different ways to represent a morph relation in databases: https://hashrocket.com/blog/posts/modeling-polymorphic-associations-in-a-relational-database

Also, Prisma our ORM, does not support morph relation right now, we will keep struggling on performing queries on child entities, we would need to re-implement our own child resolution layer.

**On the frontend side**, yes, it will make things a bit more trickier, we will have to manipulate object like:
`ActivityTarget & { people: Pick<Person>[], companies: Pick<Company>[] }` but it is also more exact on what we are manipulating and a Company is not the same thing as a Person. We can indeed create an interface when it makes sense: for example `PickableActivityTarget` for our Relation picker that would be what you describe above, but this to the component using the entity to decide of what types he wants to manipulate.

In the Relation picker example manipulating ActivityTargets, we would get `ActivityTarget & { people: Pick<Person>[], companies: Pick<Company>[] }` from graphql, then explicitely convert it to `ActivityTarget & { targets: PickableActivityTarget[]}`, and when we are displaying a PersonChip, we use: `Pick<Person>`.

<img width="754" alt="image" src="https://github.com/twentyhq/twenty/assets/12035771/ad65a674-7838-4d6b-849e-ce397d0330d9">

**Comment by emilienchvt** [comment]
Ok, I wrongly assumed interfaces were available in Prisma: **they aren't,** just like union types.
We can't either have a single `XXXXableableId` to point to all models in the style of:
```
model PipelineProgress {
  ...
  progressableId   String
  company Company? @relation("CompanyPipelineProgress", fields: [progressableId], references: [id])
  person  Person?  @relation("PersonPipelineProgress", fields: [progressableId], references: [id])
}
```
as it would violate foreign key constraints.
Initial plan is the way to go then 👌

**Comment by charlesBochet** [comment]
This has been implemented!
