### ISSUE TITLE
Profile Picture - File not found in Settings

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#8601]
# Current behavior

{"error":"File not found"} when connected with Google

![Image](https://github.com/user-attachments/assets/bddb5003-6567-4e28-a1bd-06c44b55e64b)

**Comment by Bonapara** [comment]
@Weiko doesn't seem related to the issue we fixed the other day 🤔

**Comment by charlesBochet** [comment]
Adding this case too
![Image](https://github.com/user-attachments/assets/5ed123a2-f6ce-475b-b6d0-5888bef748ee)

**Comment by mdrazak2001** [comment]
Hi @charlesBochet  @Bonapara ,
The issue lies in the getImageAbsoluteURI utility. There are multiple versions in the codebase. The correct one appends query parameters directly, while the buggy one uses URL.toString(), which encodes ? as %3F, breaking URLs.

Would you like me to create a PR to fix this issue?

**Comment by charlesBochet** [comment]
Indeed @mdrazak2001 I agree it seems to be the root cause

**Comment by charlesBochet** [comment]
I have opened a PR here: 
https://github.com/twentyhq/twenty/compare/fix-images-missing?expand=1
