### ISSUE TITLE
Currency Search

### ISSUE THREAD

**Issue by guillim** [twentyhq/twenty#8647]
# We would like to have the Search feature in Currency field metadata

## Current behavior

You need to scroll down, and it can be very long to select currencies at the bottom of the dropdown

**Example:**
 
![Image](https://github.com/user-attachments/assets/56aee440-b1e0-4fee-bcd0-9348984740cb)

![Image](https://github.com/user-attachments/assets/efee38f7-bac1-41f9-9d67-71d72f9c8d2d)

## Expected behavior
Search bar like on the Country selection dropdown

## Technical inputs

We should try to see if the option exist on the current component, and then add it. Otherwise, we should have a look at the other existing components to find one that would match the requirements. Last case scneario, let's create a dedicated component

As view with @Bonapara

**Comment by Bellahuang3715** [comment]
Hi, I would like to take on this issue, can you please assign it to me? Thank you!

**Comment by FelixMalfait** [comment]
Sure @Bellahuang3715 thanks!

**Comment by BOHEUS** [comment]
Related to #7038 (it should be implemented then according to tasks list but for some reason it wasn't)

**Comment by guillim** [comment]
Did you start working on it @Bellahuang3715 ?

**Comment by harshrajeevsingh** [comment]
Hi @guillim I see there is no update yet. So, I would like to work on this. 

![Image](https://github.com/user-attachments/assets/88c5d9fe-cc5e-466d-8044-f1a34a77f3b0)


1. The `Select` component already accepts `withSearchInput`. So we can directly use that. 
2. For #8649, I think it would be better to use `MenuItemSelect` instead of `MenuItem` inside the `Select` component. It would be useful across all the select dropdowns. For example: 

![Image](https://github.com/user-attachments/assets/976f3619-6a38-4e3d-8882-1f7b55dff317)
![Image](https://github.com/user-attachments/assets/c6934fcd-58f8-4535-a9fb-6b79ccec8ad0)

**Comment by guillim** [comment]
@harshrajeevsingh I agree, let's try to reuse the components from twenty-ui in order to achieve this issue. You can start working on this currency search issue if you want. I will be active on it as well, so don't hesitate to ping me and we can collaborate here to decide which component is best to re-use !

**Comment by harshrajeevsingh** [comment]
@guillim Sure! I will take a look at this tomorrow and will let you know which could be the best reusable component to tackle both the issues.

**Comment by harshrajeevsingh** [comment]
@guillim I looked into this again and I still think that using `MenuItemSelect` instead of `MenuItem` in the `Select` component is a better choice. Here is why: 

1. First of all we get an `IconCheck`. 
2. It uses `StyledMenuItemBase`, so the text will get truncated on smaller/fixed width's dropdown and on hover we get the desired tooltip giving the full context. So, now we can remove the dropdown width's 'auto' and use a fixed width without making the dropdown look broader. 

Here I made changes for the #8751 
Lemme know if it looks good! 

![Image](https://github.com/user-attachments/assets/22270811-6667-43a4-a0f5-f86f540710bd)

**Comment by guillim** [comment]
where are the changes #8751 points to an already closed pr

**Comment by harshrajeevsingh** [comment]
@guillim I don't see it anymore. I'm on the main branch. Can you recheck from your side?

![Image](https://github.com/user-attachments/assets/b1f812b9-05f3-493f-adb6-22d41a7c543d)

**Comment by guillim** [comment]
I see this on the main branch, which is the current behaviour described at the top of this issue. So everything's normal. We still need to do the feature :)

<img width="651" alt="Image" src="https://github.com/user-attachments/assets/5ae603f9-6e06-4f24-9feb-af2d5a33aa08" />

**Comment by harshrajeevsingh** [comment]
@guillim I made a PR here #9179
Sorry for the delay! I was busy with personal work. But I will be active from now onwards :)
