### ISSUE TITLE
Incorrect Database Connection String in .env File

### ISSUE THREAD

**Issue by Lucifer4255** [twentyhq/twenty#8741]
The default database connection string provided in the .env file for the twenty repository appears to be incorrect. Specifically, the connection string causes authentication failures when attempting to connect to PostgreSQL.

**Steps to Reproduce:**
Clone the repository and set up the environment using the provided .env file.
Run the application or attempt a database connection.
Observe authentication failure due to an incorrect connection string format or credentials.
![Image](https://github.com/user-attachments/assets/d8900943-4ba7-4d4d-8a1f-5c0870821acb)
![Image](https://github.com/user-attachments/assets/e6861b3d-4296-464f-99c7-0ba5894e9f63)

**Expected Behavior:**
The application should connect successfully to the PostgreSQL database using the provided .env configuration.

**Suggested Fix:**
Verify and update the default connection string in the .env file to ensure it follows the correct format:
`postgres://<username>:<password>@<host>:<port>/<database>`

if possible i can work in this issue

**Comment by FelixMalfait** [comment]
Good point, it's because docker's default is postgres:twenty (we use the Postgres super user), but the local setup (brew, wsl, etc.) defaults to using postgres:postgres  ; we should probably just use postgres:postgres everywhere remove drop the instrusctions in the doc to create a twenty user (since it's a local setup anyway)

**Comment by BOHEUS** [comment]
@Lucifer4255 go ahead, I'll review it

**Comment by ehconitin** [comment]
closed in #8801
