### ISSUE TITLE
Strange behavior when deleting a large number of records

### ISSUE THREAD

**Issue by FelixMalfait** [twentyhq/twenty#9018]
I had a page with 2000 records.
I tried to delete all of them except the 3 most recent ones.
On the UI it seemed like everything went well, I saw 1997 were selected.
Then when I clicked "delete" it started entering a weird mode, I think it tried to fetch the 2000 records locally at first, making my browser slow (but without giving me any feedback that the operation was in progress), then deleting them. 
It seems like the 2000 records were soft-deleted and not 1997 like I asked to.

**Comment by shan-max** [comment]
the DC was ABSORBING.

**Comment by bosiraphael** [comment]
There is actually two issues within this one:
- The fact that the browser is slow: this is due to the fact that when we delete multiple records we loop on the favorites to delete them because we still don't have cascade delete for relations.
Proposed solution: Enqueue a job which will batch delete favorites and optimistically delete them in the front.

- The second issue is the fact that the wrong number of record is being deleted. I still have to find where this issue is coming from.
