### ISSUE TITLE
Edit picture style on people detail page

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#906]
People placeholder picture should be round (All people's pictures should be round).
Font size should be 16px medium.
Square should be 40px

![Image](https://github.com/twentyhq/twenty/assets/19412894/bbda5f92-4165-4ef8-8098-59502f6083c7)

**Comment by nsv23** [comment]
Hi, I would like to work on this issue.

**Comment by FelixMalfait** [comment]
Hey @nsv23 thanks a lot ; sorry this was still open. I realize it has been fixed by @310387 a few days ago!

Here are similar frontend issues that should be easy to get started: 
https://github.com/twentyhq/twenty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+label%3Afront+label%3A%22quick+win%22+no%3Aassignee
Let me know if I should assign you any of them!
