### ISSUE TITLE
All tasks do not show when creating task by status kanban

### ISSUE THREAD

**Issue by phjackl3** [twentyhq/twenty#9095]
## Bug Description

When tasks are grouped by Status, all tasks do not show in the view

**Example:** 
I have a long list of tasks, with most of them set to status 'TO DO'
![Image](https://github.com/user-attachments/assets/70d9a623-a0ad-4b97-99f6-8d0e0cb1c9b4)
I have a view that groups by Status. I expect all the tasks to be shown in that view. But the number of tasks in the 'TO DO' Status is truncated to 10.
![Image](https://github.com/user-attachments/assets/c777ed0f-e04b-4781-a3ff-ca7c8b236de9)

## Expected behavior

All tasks that are in the table view should appear in the Kanban view

**Comment by FurquanAnwer** [comment]
Please assign me this issue !

**Comment by pacyL2K19** [comment]
Is this really an issue?
It seems like there is a pagination that limits the list of items by 10 per status, and when I reach the bottom of the list, it triggers a new API call with variables like:
```
{
    "filter": {
        "status": {
            "in": [
                "TODO"
            ]
        }
    },
    "orderBy": [
        {
            "position": "AscNullsFirst"
        }
    ],
    "lastCursor": "eyJwb3NpdGlvbiI6LTEwLCJpZCI6ImU1MzRhN2FiLTQ1YTEtNGQ3NS05ODZlLWI4Mzc4ZGE0MDQ5ZCJ9",
    "limit": 10
}

# and

{
    "filter": {
        "status": {
            "in": [
                "IN_PROGRESS"
            ]
        }
    },
    "orderBy": [
        {
            "position": "AscNullsFirst"
        }
    ],
    "lastCursor": "eyJwb3NpdGlvbiI6LTEyLCJpZCI6IjFhZDEzNTQ1LWUwNzctNGNkZi1hMTIxLTM1MmIxY2M3N2U5ZCJ9",
    "limit": 10
}
```
Is this behavior intentional (what I assume), or should we work on this as an issue, fetching all the records once (as it's done in the `All Tasks` view)?
@FelixMalfait

**Comment by FelixMalfait** [comment]
Thanks @pacyL2K19 you're right the pagination behavior is intentional.

The aggregate count might have been wrong bug that has likely been fixed with the new aggregate feature  since we recoded that part from scratch (`IS_AGGREGATE_QUERY_ENABLED` feature flag). It might make it for this week's release. Most likely it will be in the early January release.
