### ISSUE TITLE
In a Phone Field settings page, after saving a default country code, going back to the page shows the previous value

### ISSUE THREAD

**Issue by Weiko** [twentyhq/twenty#9229]
## Bug Description

https://github.com/user-attachments/assets/77085619-99fe-48da-a598-95d4600d5ab7

**Comment by muraliSingh7** [comment]
@guillim 
Path: `twenty/packages/twenty-front/src/pages/settings/data-model/SettingsObjectFieldEdit.tsx`
Line number 131: `updateOneFieldMetadataItem` is throwing error.
Error Message: ApolloError: Cannot return null for non-nullable field field.id.

**Comment by yadavshubham01** [comment]
hey @Weiko i want to work on this issue please assign me ??

**Comment by Weiko** [comment]
Hi @yadavshubham01, sure feel free to try it. Thank you.

**Comment by yadavshubham01** [comment]
@guillim Work on it I open pr today

**Comment by yadavshubham01** [comment]
hey @guillim when i test this code in https://demo.twenty.com/ in this after update it correctly show update country code i can't find any error ?? may you can solve it

**Comment by guillim** [comment]
Sorry I am a bit confuse. Are you saying that you cannot reproduce the error ?

**Comment by yadavshubham01** [comment]
yes

**Comment by guillim** [comment]
So after a difficult investigation, there was a bug introduced by this [PR](https://github.com/twentyhq/twenty/pull/9157/files#diff-8119cbba70993400d2f451fbdbedc2ec898b2dac964d3ec13817c76d1453cf7d) so your opinion will be valuable @AMoreaux 😸

*Description*
The bug is larger than the phone settings. It's actually every update of metadata that deletes the recoil `objectmetadataitems` which loads the mock values.

*Solution*
in the file **useUpdateOneFieldMetadataItem** removing `setCurrentWorkspace(data?.currentUser?.defaultWorkspace);` solves the issue. Not sure of side effects though

**Comment by AMoreaux** [comment]
Yes defaultWorkspace not exist anymore since now you can be authenticated on multiple workspace at the same time. So your suggestion is 100% logic
