### ISSUE TITLE
Edit dark mode continue with Google button style

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#948]
# Current design

Connect with Google button appears with a white background on dark mode:
![Image](https://github.com/twentyhq/twenty/assets/19412894/7bea94c3-fa8e-4e11-adfa-fc67e169aa38)

# Desired designed

### color
Should have the same look that the Light mode button:
![Image](https://github.com/twentyhq/twenty/assets/19412894/ff8f5fe7-78d3-402f-bd5a-5c91fdf8bffc)

### hover
Make sure to add the hover behavior on the button:

https://github.com/twentyhq/twenty/assets/19412894/3f8b9ee2-d318-4a82-918e-3b0b15120f2a

**Comment by AjayVijendran** [comment]
Hello @Bonapara @FelixMalfait . I am new to open-source contributions. I see this as a good task to get started with. Can i take up this?

**Comment by FelixMalfait** [comment]
@AjayVijendran thanks for offering to help! This is a great issue to start with. I'll assign it to you
Feel free to ask on Discord if you need help

**Comment by charlesBochet** [comment]
@AjayVijendran, any update on this one? :)

**Comment by Palakkgoyal** [comment]
@charlesBochet Can I take this up?

**Comment by charlesBochet** [comment]
@Palakkgoyal are you working on this one?

**Comment by Palakkgoyal** [comment]
I was not able to set up this project. You can move the issue to someone else. Apology for not informing.

**Comment by FelixMalfait** [comment]
No problem @Palakkgoyal if there's any way we can help you setup the project feel free to ask on Discord or open an issue

**Comment by yashug** [comment]
@charlesBochet can you please assign this to me ?

**Comment by FelixMalfait** [comment]
Thanks a lot @yashug

**Comment by yashug** [comment]
@FelixMalfait can you please provide more info on about the colors we need to use. MainButton using radial gradient background.

**Comment by charlesBochet** [comment]
@Bonapara could you help here :)

**Comment by FelixMalfait** [comment]
Hey @yashug
There are two things we'd like to change:
* For the dark mode, we want the button to look like the light mode (so instead of being white, use the same style as in your first screenshot)
* For both mode, introduce an hover effect

If you're logged in to Figma I think you can use the dev mode on this file: https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?node-id=2508%3A89576&mode=dev

Copying screenshots in case you don't manage to get access:
<img width="935" alt="Screenshot 2023-09-18 at 21 54 20" src="https://github.com/twentyhq/twenty/assets/6399865/0a8a1903-3534-410d-80a9-9b7527735f69">
<img width="936" alt="Screenshot 2023-09-18 at 21 54 45" src="https://github.com/twentyhq/twenty/assets/6399865/1abf4636-926a-4ec2-9865-8a4b8da5284f">

```
border-radius: var(--spacing-8-px, 8px);
border: 1px solid var(--transparent-light, rgba(0, 0, 0, 0.04));
background: radial-gradient(76.32% 95.59% at 50% 0%, #505050 0%, #333 100%);
/* BoxShadow/light/Light */
box-shadow: 0px 2px 4px 0px rgba(0, 0, 0, 0.04), 0px 0px 4px 0px rgba(0, 0, 0, 0.08);
```

**Comment by yashug** [comment]
@FelixMalfait thanks for the detailed help
