### ISSUE TITLE
Add the workspace logo on Twenty logo on the invited route

### ISSUE THREAD

**Issue by Bonapara** [twentyhq/twenty#953]
# Desired behavior

- If someone invites me with a link, I should land on a sign-up page with the workspace logo I've been invited to, displayed on the Twenty logo.
- The title of the popup should also be adapted "Join XXX team" (XXX being the workspace name you've been invited to)

![Image](https://github.com/twentyhq/twenty/assets/19412894/05a1b2a8-618a-4365-9b28-cd4d9b0e84fc)

Figma:
https://www.figma.com/file/xt8O9mFeLl46C5InWwoMrN/Twenty?type=design&node-id=5281-55747&mode=design&t=sj4NhD0g7qMJY0yH-4
```[tasklist]
### Tasks
- [ ] Make a GraphQL call to get the workspace and its logo based on inviteHash
- [ ] If the workspace is not found, display a toast (snackbar) and redirect to sign-up
```

**Comment by FelixMalfait** [comment]
I don't think we have an endpoint to retrieve the workspace logo/name through an auth code and without authentication, so this involves backend work, not just frontend work!  (we need the endpoint to ask for the auth code because we don't want to create a security issue by allowing someone to list all of our workspaces)
